/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.viewreservaciones;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author emmez
 */
public class FrameDetallesReservacion extends javax.swing.JFrame {

    /**
     * Creates new form FrameDetallesReservacion
     */
    public FrameDetallesReservacion() {
        initComponents();
        setIconImage(getIconImage());
    }
    
    @Override
    public Image getIconImage () {  
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/imagesviewprincipal/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImagenRoE = new javax.swing.JLabel();
        labelImagenCoE = new javax.swing.JLabel();
        panelDatosR = new javax.swing.JPanel();
        panelDatosCoE = new javax.swing.JPanel();
        labelTItuloP = new javax.swing.JLabel();
        labelTItuloR = new javax.swing.JLabel();
        labelDatosRoE = new javax.swing.JLabel();
        labelDatosCoE = new javax.swing.JLabel();
        botonEliminar = new javax.swing.JButton();
        fondoBotonEliminar = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        fondoBotonGuardar = new javax.swing.JLabel();
        labelGris = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelImagenRoE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/imagenReservacion.png"))); // NOI18N
        getContentPane().add(labelImagenRoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        labelImagenCoE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/imagenComensal.png"))); // NOI18N
        getContentPane().add(labelImagenCoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        panelDatosR.setOpaque(false);
        getContentPane().add(panelDatosR, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 330, 540));

        panelDatosCoE.setOpaque(false);
        getContentPane().add(panelDatosCoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 330, 530));

        labelTItuloP.setBackground(new java.awt.Color(0, 0, 0));
        labelTItuloP.setFont(new java.awt.Font("Open Sans Medium", 1, 16)); // NOI18N
        labelTItuloP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTItuloP.setText("COMENSAL");
        getContentPane().add(labelTItuloP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 210, 40));

        labelTItuloR.setBackground(new java.awt.Color(0, 0, 0));
        labelTItuloR.setFont(new java.awt.Font("Open Sans Medium", 1, 16)); // NOI18N
        labelTItuloR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTItuloR.setText("RESERVACIÓN");
        getContentPane().add(labelTItuloR, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 220, 40));

        labelDatosRoE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/datosRoE.png"))); // NOI18N
        getContentPane().add(labelDatosRoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        labelDatosCoE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/datosCoE.png"))); // NOI18N
        getContentPane().add(labelDatosCoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        botonEliminar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(230, 231, 235));
        botonEliminar.setBorder(null);
        botonEliminar.setBorderPainted(false);
        botonEliminar.setContentAreaFilled(false);
        botonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEliminarMouseExited(evt);
            }
        });
        getContentPane().add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, 70, 60));

        fondoBotonEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoBotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/botonEliminar.png"))); // NOI18N
        getContentPane().add(fondoBotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, 70, 60));

        botonGuardar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(230, 231, 235));
        botonGuardar.setBorder(null);
        botonGuardar.setBorderPainted(false);
        botonGuardar.setContentAreaFilled(false);
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGuardarMouseExited(evt);
            }
        });
        getContentPane().add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 570, 70, 60));

        fondoBotonGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoBotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/botonGuardar.png"))); // NOI18N
        getContentPane().add(fondoBotonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 570, 70, 60));

        labelGris.setBackground(new java.awt.Color(39, 45, 47));
        labelGris.setOpaque(true);
        getContentPane().add(labelGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseEntered
        // TODO add your handling code here:
        fondoBotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/botonGuardarPresionado.png")));
    }//GEN-LAST:event_botonGuardarMouseEntered

    private void botonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseExited
        // TODO add your handling code here:
        fondoBotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/botonGuardar.png")));
    }//GEN-LAST:event_botonGuardarMouseExited

    private void botonEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseEntered
        // TODO add your handling code here:
        fondoBotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/botonEliminarPresionado.png")));
    }//GEN-LAST:event_botonEliminarMouseEntered

    private void botonEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseExited
        // TODO add your handling code here:
        fondoBotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/botonEliminar.png")));
    }//GEN-LAST:event_botonEliminarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDetallesReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDetallesReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDetallesReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDetallesReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDetallesReservacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonEliminar;
    public javax.swing.JButton botonGuardar;
    private javax.swing.JLabel fondoBotonEliminar;
    private javax.swing.JLabel fondoBotonGuardar;
    private javax.swing.JLabel labelDatosCoE;
    private javax.swing.JLabel labelDatosRoE;
    private javax.swing.JLabel labelGris;
    private javax.swing.JLabel labelImagenCoE;
    private javax.swing.JLabel labelImagenRoE;
    public javax.swing.JLabel labelTItuloP;
    public javax.swing.JLabel labelTItuloR;
    public javax.swing.JPanel panelDatosCoE;
    public javax.swing.JPanel panelDatosR;
    // End of variables declaration//GEN-END:variables
}
