/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewreservaciones;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import model.modelview.MyComboBoxRender;

/**
 *
 * @author emmez
 */
public class PanelEvento extends javax.swing.JPanel {

    /**
     * Creates new form PanelComensal
     */
    public PanelEvento() {
        initComponents();
        comboBoxMetodo.setOpaque(false);
        comboBoxMetodo.setEditable(true);
        JTextField boxField = (JTextField)comboBoxMetodo.getEditor().getEditorComponent();
        boxField.setBorder(BorderFactory.createEmptyBorder());
        boxField.setForeground(new Color(230,231,235));
        boxField.setBackground(new Color(0, 0, 0, 0));
        boxField.setFocusable(false);
        comboBoxMetodo.setRenderer(new MyComboBoxRender());
        
        comboBoxEstatus.setOpaque(false);
        comboBoxEstatus.setEditable(true);
        boxField = (JTextField)comboBoxEstatus.getEditor().getEditorComponent();
        boxField.setBorder(BorderFactory.createEmptyBorder());
        boxField.setForeground(new Color(230,231,235));
        boxField.setBackground(new Color(0, 0, 0, 0));
        boxField.setFocusable(false);
        comboBoxEstatus.setRenderer(new MyComboBoxRender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextPane();
        labelSsexo = new javax.swing.JLabel();
        labelMontoN1 = new javax.swing.JLabel();
        labelMontoN = new javax.swing.JLabel();
        labelMontoA1 = new javax.swing.JLabel();
        labelMontoA = new javax.swing.JLabel();
        labelEstatus = new javax.swing.JLabel();
        labelMetodo = new javax.swing.JLabel();
        labelHCierre = new javax.swing.JLabel();
        labelHInicio = new javax.swing.JLabel();
        labelCantidadN1 = new javax.swing.JLabel();
        labelCantidadN = new javax.swing.JLabel();
        labelCantidadA1 = new javax.swing.JLabel();
        labelCantidadA = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelMontoTotal = new javax.swing.JLabel();
        spinnerMontoAdulto = new javax.swing.JSpinner();
        spinnerMontoNino = new javax.swing.JSpinner();
        spinnerNumAdultos = new javax.swing.JSpinner();
        spinnerNumNinos = new javax.swing.JSpinner();
        comboBoxEstatus = new javax.swing.JComboBox<>();
        comboBoxMetodo = new javax.swing.JComboBox<>();
        labelMetodo1 = new javax.swing.JLabel();
        spinnerHoraInicio = new javax.swing.JSpinner();
        spinnerHoraCierre = new javax.swing.JSpinner();
        labelEstatus1 = new javax.swing.JLabel();
        jDateFechaR = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(102, 102, 102));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMotivo.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtMotivo.setForeground(new java.awt.Color(230, 231, 235));
        jScrollPane1.setViewportView(txtMotivo);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 220, 70));

        labelSsexo.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelSsexo.setForeground(new java.awt.Color(230, 231, 235));
        labelSsexo.setText("Motivo:");
        add(labelSsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        labelMontoN1.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelMontoN1.setForeground(new java.awt.Color(230, 231, 235));
        labelMontoN1.setText("Monto");
        add(labelMontoN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        labelMontoN.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelMontoN.setForeground(new java.awt.Color(230, 231, 235));
        labelMontoN.setText("Niño($):");
        add(labelMontoN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        labelMontoA1.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelMontoA1.setForeground(new java.awt.Color(230, 231, 235));
        labelMontoA1.setText("Adulto($):");
        add(labelMontoA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 80, -1));

        labelMontoA.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelMontoA.setForeground(new java.awt.Color(230, 231, 235));
        labelMontoA.setText("Monto");
        add(labelMontoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 80, -1));

        labelEstatus.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelEstatus.setForeground(new java.awt.Color(230, 231, 235));
        labelEstatus.setText("Estatus:");
        add(labelEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        labelMetodo.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelMetodo.setForeground(new java.awt.Color(230, 231, 235));
        labelMetodo.setText("de pago:");
        add(labelMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        labelHCierre.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelHCierre.setForeground(new java.awt.Color(230, 231, 235));
        labelHCierre.setText("Hora cierre:");
        add(labelHCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        labelHInicio.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelHInicio.setForeground(new java.awt.Color(230, 231, 235));
        labelHInicio.setText("Hora inicio:");
        add(labelHInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        labelCantidadN1.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelCantidadN1.setForeground(new java.awt.Color(230, 231, 235));
        labelCantidadN1.setText("Niños:");
        add(labelCantidadN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        labelCantidadN.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelCantidadN.setForeground(new java.awt.Color(230, 231, 235));
        labelCantidadN.setText("Número de");
        add(labelCantidadN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        labelCantidadA1.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelCantidadA1.setForeground(new java.awt.Color(230, 231, 235));
        labelCantidadA1.setText("Adultos:");
        add(labelCantidadA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 80, -1));

        labelCantidadA.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelCantidadA.setForeground(new java.awt.Color(230, 231, 235));
        labelCantidadA.setText("Número de");
        add(labelCantidadA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 90, -1));

        labelTotal.setFont(new java.awt.Font("Open Sans SemiBold", 0, 18)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(230, 231, 235));
        labelTotal.setText("Total");
        add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 60, 30));

        labelMontoTotal.setFont(new java.awt.Font("Open Sans SemiBold", 0, 18)); // NOI18N
        labelMontoTotal.setForeground(new java.awt.Color(254, 114, 76));
        labelMontoTotal.setText("115$");
        add(labelMontoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 90, 30));

        spinnerMontoAdulto.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        spinnerMontoAdulto.setModel(new javax.swing.SpinnerNumberModel(55, 0, 100, 1));
        add(spinnerMontoAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 70, 40));

        spinnerMontoNino.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        spinnerMontoNino.setModel(new javax.swing.SpinnerNumberModel(15, 0, 100, 1));
        add(spinnerMontoNino, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 70, 40));

        spinnerNumAdultos.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        spinnerNumAdultos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        add(spinnerNumAdultos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 70, 40));

        spinnerNumNinos.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        spinnerNumNinos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        add(spinnerNumNinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 70, 40));

        comboBoxEstatus.setBackground(new java.awt.Color(86, 92, 94));
        comboBoxEstatus.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        comboBoxEstatus.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona estatus", "Pendiente por pagar", "Pagado" }));
        comboBoxEstatus.setBorder(null);
        comboBoxEstatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comboBoxEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 220, 40));

        comboBoxMetodo.setBackground(new java.awt.Color(86, 92, 94));
        comboBoxMetodo.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        comboBoxMetodo.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona método de pago", "Efectivo", "Zelle", "Pago móvil", "PayPal" }));
        comboBoxMetodo.setBorder(null);
        comboBoxMetodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comboBoxMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 220, 40));

        labelMetodo1.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelMetodo1.setForeground(new java.awt.Color(230, 231, 235));
        labelMetodo1.setText("Método");
        add(labelMetodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        spinnerHoraInicio.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        spinnerHoraInicio.setModel(new javax.swing.SpinnerNumberModel(55, 0, 100, 1));
        add(spinnerHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 160, 40));

        spinnerHoraCierre.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        spinnerHoraCierre.setModel(new javax.swing.SpinnerNumberModel(15, 0, 100, 1));
        add(spinnerHoraCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 160, 40));

        labelEstatus1.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelEstatus1.setForeground(new java.awt.Color(230, 231, 235));
        labelEstatus1.setText("Fecha: ");
        add(labelEstatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, -1));

        jDateFechaR.setFont(new java.awt.Font("Open Sans Medium", 0, 13)); // NOI18N
        add(jDateFechaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 220, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> comboBoxEstatus;
    public javax.swing.JComboBox<String> comboBoxMetodo;
    public com.toedter.calendar.JDateChooser jDateFechaR;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCantidadA;
    private javax.swing.JLabel labelCantidadA1;
    private javax.swing.JLabel labelCantidadN;
    private javax.swing.JLabel labelCantidadN1;
    private javax.swing.JLabel labelEstatus;
    private javax.swing.JLabel labelEstatus1;
    private javax.swing.JLabel labelHCierre;
    private javax.swing.JLabel labelHInicio;
    private javax.swing.JLabel labelMetodo;
    private javax.swing.JLabel labelMetodo1;
    private javax.swing.JLabel labelMontoA;
    private javax.swing.JLabel labelMontoA1;
    private javax.swing.JLabel labelMontoN;
    private javax.swing.JLabel labelMontoN1;
    public javax.swing.JLabel labelMontoTotal;
    private javax.swing.JLabel labelSsexo;
    private javax.swing.JLabel labelTotal;
    public javax.swing.JSpinner spinnerHoraCierre;
    public javax.swing.JSpinner spinnerHoraInicio;
    public javax.swing.JSpinner spinnerMontoAdulto;
    public javax.swing.JSpinner spinnerMontoNino;
    public javax.swing.JSpinner spinnerNumAdultos;
    public javax.swing.JSpinner spinnerNumNinos;
    public javax.swing.JTextPane txtMotivo;
    // End of variables declaration//GEN-END:variables
}
