/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewreservaciones;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import model.modelview.MyComboBoxRender;

/**
 *
 * @author emmez
 */
public class PanelRegistrarComensal extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsultarReservaciones
     */
    public PanelRegistrarComensal() {
        initComponents();
        comboBoxMunicipio .setOpaque(false);
        comboBoxMunicipio.setEditable(true);
        JTextField boxField = (JTextField)comboBoxMunicipio .getEditor().getEditorComponent();
        boxField.setBorder(BorderFactory.createEmptyBorder());
        boxField.setForeground(new Color(230,231,235));
        boxField.setBackground(new Color(0, 0, 0, 0));
        boxField.setFocusable(false);
        comboBoxMunicipio.setRenderer(new MyComboBoxRender());
        
        comboBoxSexo .setOpaque(false);
        comboBoxSexo.setEditable(true);
        boxField = (JTextField)comboBoxSexo .getEditor().getEditorComponent();
        boxField.setBorder(BorderFactory.createEmptyBorder());
        boxField.setForeground(new Color(230,231,235));
        boxField.setBackground(new Color(0, 0, 0, 0));
        boxField.setFocusable(false);
        comboBoxSexo.setRenderer(new MyComboBoxRender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegistrar = new javax.swing.JButton();
        fondoBotonRegistrar = new javax.swing.JLabel();
        comboBoxSexo = new javax.swing.JComboBox<>();
        labelInputSexo = new javax.swing.JLabel();
        spinnerEdad = new javax.swing.JSpinner();
        labelInputEdad = new javax.swing.JLabel();
        comboBoxMunicipio = new javax.swing.JComboBox<>();
        labelInputMunicipio = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        labelInputTelefono = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        labelInputCedula = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        labelInputCorreo = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        labelInputApellido = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        labelInputNombre = new javax.swing.JLabel();
        labelImagen = new javax.swing.JLabel();
        labelTItulo = new javax.swing.JLabel();
        labelFondoTitulo = new javax.swing.JLabel();
        labelFondoPanel = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        fondoBotonRegresar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(39, 45, 47));
        setForeground(new java.awt.Color(230, 231, 235));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRegistrar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(39, 45, 47));
        botonRegistrar.setText("Registrar");
        botonRegistrar.setBorder(null);
        botonRegistrar.setBorderPainted(false);
        botonRegistrar.setContentAreaFilled(false);
        botonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseExited(evt);
            }
        });
        add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, 140, 60));

        fondoBotonRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoBotonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/botonAmarillo.png"))); // NOI18N
        add(fondoBotonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 160, 60));

        comboBoxSexo.setBackground(new java.awt.Color(86, 92, 94));
        comboBoxSexo.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        comboBoxSexo.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        comboBoxSexo.setBorder(null);
        comboBoxSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 482, 170, 40));

        labelInputSexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/inputPequeEoC.png"))); // NOI18N
        add(labelInputSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, -1, -1));

        spinnerEdad.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        spinnerEdad.setModel(new javax.swing.SpinnerNumberModel(30, 18, 90, 1));
        add(spinnerEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 482, 170, 40));

        labelInputEdad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/inputPequeEoC.png"))); // NOI18N
        add(labelInputEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));

        comboBoxMunicipio.setBackground(new java.awt.Color(86, 92, 94));
        comboBoxMunicipio.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        comboBoxMunicipio.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el municipio", "Baruta", "Chacao", "El Hatillo", "Libertador", "Sucre" }));
        comboBoxMunicipio.setBorder(null);
        comboBoxMunicipio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comboBoxMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 412, 370, 40));

        labelInputMunicipio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/inputGrandeEoP.png"))); // NOI18N
        add(labelInputMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        txtTelefono.setBackground(new java.awt.Color(0,0,0,1));
        txtTelefono.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtTelefono.setForeground(java.awt.Color.lightGray);
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelefono.setText("Teléfono");
        txtTelefono.setBorder(null);
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 342, 160, 40));

        labelInputTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/inputPequeEoC.png"))); // NOI18N
        add(labelInputTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        txtCedula.setBackground(new java.awt.Color(0,0,0,1));
        txtCedula.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtCedula.setForeground(java.awt.Color.lightGray);
        txtCedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCedula.setText("Cédula");
        txtCedula.setBorder(null);
        txtCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedulaMousePressed(evt);
            }
        });
        add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 342, 160, 40));

        labelInputCedula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/inputPequeEoC.png"))); // NOI18N
        add(labelInputCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(0,0,0,1));
        txtCorreo.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtCorreo.setForeground(java.awt.Color.lightGray);
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCorreo.setText("Correo");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 360, 40));

        labelInputCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/inputGrandeEoP.png"))); // NOI18N
        add(labelInputCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        txtApellido.setBackground(new java.awt.Color(0,0,0,1));
        txtApellido.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtApellido.setForeground(java.awt.Color.lightGray);
        txtApellido.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellido.setText("Apellido");
        txtApellido.setBorder(null);
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoMousePressed(evt);
            }
        });
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 202, 160, 40));

        labelInputApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/inputPequeEoC.png"))); // NOI18N
        add(labelInputApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));

        txtNombre.setBackground(new java.awt.Color(0,0,0,1));
        txtNombre.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtNombre.setForeground(java.awt.Color.lightGray);
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setText("Nombre");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 202, 160, 40));

        labelInputNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/inputPequeEoC.png"))); // NOI18N
        add(labelInputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        labelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/imagenComensal.png"))); // NOI18N
        add(labelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        labelTItulo.setBackground(new java.awt.Color(0, 0, 0));
        labelTItulo.setFont(new java.awt.Font("Open Sans Medium", 1, 18)); // NOI18N
        labelTItulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTItulo.setText("DATOS DEL COMENSAL");
        add(labelTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 440, 50));

        labelFondoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/fondoTituloAmarillo.png"))); // NOI18N
        add(labelFondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        labelFondoPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/fondoComensal.png"))); // NOI18N
        add(labelFondoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        botonRegresar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonRegresar.setForeground(new java.awt.Color(230, 231, 235));
        botonRegresar.setBorder(null);
        botonRegresar.setBorderPainted(false);
        botonRegresar.setContentAreaFilled(false);
        botonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresarMouseExited(evt);
            }
        });
        add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 50, 50));

        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/botonRegresar.png"))); // NOI18N
        add(fondoBotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        // TODO add your handling code here:
        if(txtNombre.getText().equals("Nombre")){
            txtNombre.setText("");
            txtNombre.setForeground(new Color(230,231,235));
        }
        
        if(txtApellido.getText().isEmpty()){
            txtApellido.setText("Apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCedula.getText().isEmpty()){
            txtCedula.setText("Cédula");
            txtCedula.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Teléfono");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMousePressed
        // TODO add your handling code here:
        if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtApellido.getText().equals("Apellido")){
            txtApellido.setText("");
            txtApellido.setForeground(new Color(230,231,235));
        }
        
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCedula.getText().isEmpty()){
            txtCedula.setText("Cédula");
            txtCedula.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Teléfono");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtApellidoMousePressed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
        if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtApellido.getText().isEmpty()){
            txtApellido.setText("Apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCorreo.getText().equals("Correo")){
            txtCorreo.setText("");
            txtCorreo.setForeground(new Color(230,231,235));
        }
        
        if(txtCedula.getText().isEmpty()){
            txtCedula.setText("Cédula");
            txtCedula.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Teléfono");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaMousePressed
        // TODO add your handling code here:
        if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtApellido.getText().isEmpty()){
            txtApellido.setText("Apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCedula.getText().equals("Cédula")){
            txtCedula.setText("");
            txtCedula.setForeground(new Color(230,231,235));
        }
        
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Teléfono");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtCedulaMousePressed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        // TODO add your handling code here:
        if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtApellido.getText().isEmpty()){
            txtApellido.setText("Apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCedula.getText().isEmpty()){
            txtCedula.setText("Cédula");
            txtCedula.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtTelefono.getText().equals("Teléfono")){
            txtTelefono.setText("");
            txtTelefono.setForeground(new Color(230,231,235));
        }
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void botonRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseEntered
        // TODO add your handling code here:
        fondoBotonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/botonAmarilloPresionado.png"))); // NOI18N
    }//GEN-LAST:event_botonRegistrarMouseEntered

    private void botonRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseExited
        // TODO add your handling code here:
        fondoBotonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/botonAmarillo.png"))); // NOI18N
    }//GEN-LAST:event_botonRegistrarMouseExited

    private void botonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseEntered
        // TODO add your handling code here:
        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/botonRegresarPresionado.png"))); // NOI18N
    }//GEN-LAST:event_botonRegresarMouseEntered

    private void botonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseExited
        // TODO add your handling code here:
        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewreservaciones/botonRegresar.png"))); // NOI18N
    }//GEN-LAST:event_botonRegresarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonRegistrar;
    public javax.swing.JButton botonRegresar;
    public javax.swing.JComboBox<String> comboBoxMunicipio;
    public javax.swing.JComboBox<String> comboBoxSexo;
    private javax.swing.JLabel fondoBotonRegistrar;
    private javax.swing.JLabel fondoBotonRegresar;
    private javax.swing.JLabel labelFondoPanel;
    private javax.swing.JLabel labelFondoTitulo;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelInputApellido;
    private javax.swing.JLabel labelInputCedula;
    private javax.swing.JLabel labelInputCorreo;
    private javax.swing.JLabel labelInputEdad;
    private javax.swing.JLabel labelInputMunicipio;
    private javax.swing.JLabel labelInputNombre;
    private javax.swing.JLabel labelInputSexo;
    private javax.swing.JLabel labelInputTelefono;
    public javax.swing.JLabel labelTItulo;
    public javax.swing.JSpinner spinnerEdad;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
