/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewreservaciones;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import model.modelview.MyComboBoxRender;

/**
 *
 * @author emmez
 */
public class PanelEmpresa extends javax.swing.JPanel {

    /**
     * Creates new form PanelComensal
     */
    public PanelEmpresa() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtRIF = new javax.swing.JTextField();
        txtMunicipio = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        labelMunicipio = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelRIF = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(0,0,0,1));
        txtNombre.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(230, 231, 235));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setText("Nombre");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 220, 40));

        txtCorreo.setEditable(false);
        txtCorreo.setBackground(new java.awt.Color(0,0,0,1));
        txtCorreo.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(230, 231, 235));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCorreo.setText("Correo");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 220, 40));

        txtRIF.setEditable(false);
        txtRIF.setBackground(new java.awt.Color(0,0,0,1));
        txtRIF.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtRIF.setForeground(new java.awt.Color(230, 231, 235));
        txtRIF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRIF.setText("Cédula");
        txtRIF.setBorder(null);
        txtRIF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtRIFMousePressed(evt);
            }
        });
        add(txtRIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 220, 40));

        txtMunicipio.setEditable(false);
        txtMunicipio.setBackground(new java.awt.Color(0,0,0,1));
        txtMunicipio.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtMunicipio.setForeground(new java.awt.Color(230, 231, 235));
        txtMunicipio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMunicipio.setText("Municipio");
        txtMunicipio.setBorder(null);
        txtMunicipio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMunicipioMousePressed(evt);
            }
        });
        add(txtMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 220, 40));

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(0,0,0,1));
        txtTelefono.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(230, 231, 235));
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelefono.setText("Teléfono");
        txtTelefono.setBorder(null);
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 220, 40));

        labelMunicipio.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelMunicipio.setForeground(new java.awt.Color(230, 231, 235));
        labelMunicipio.setText("Municipio:");
        add(labelMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        labelTelefono.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelTelefono.setForeground(new java.awt.Color(230, 231, 235));
        labelTelefono.setText("Telefono:");
        add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        labelRIF.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelRIF.setForeground(new java.awt.Color(230, 231, 235));
        labelRIF.setText("RIF");
        add(labelRIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        labelCorreo.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelCorreo.setForeground(new java.awt.Color(230, 231, 235));
        labelCorreo.setText("Correo:");
        add(labelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        labelNombre.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(230, 231, 235));
        labelNombre.setText("Nombre:");
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
 
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtRIFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRIFMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRIFMousePressed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void txtMunicipioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMunicipioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMunicipioMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelMunicipio;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRIF;
    private javax.swing.JLabel labelTelefono;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtMunicipio;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtRIF;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
