/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewreservaciones;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import model.modelview.MyComboBoxRender;

/**
 *
 * @author emmez
 */
public class PanelComensal extends javax.swing.JPanel {

    /**
     * Creates new form PanelComensal
     */
    public PanelComensal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        labelSsexo = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        labelMunicipio = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelCedula = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        txtMunicipio = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 102, 102));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(0,0,0,1));
        txtNombre.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(230, 231, 235));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setText("Nombre");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 210, 40));

        txtApellido.setEditable(false);
        txtApellido.setBackground(new java.awt.Color(0,0,0,1));
        txtApellido.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(230, 231, 235));
        txtApellido.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellido.setText("Apellido");
        txtApellido.setBorder(null);
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoMousePressed(evt);
            }
        });
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 210, 40));

        txtCorreo.setEditable(false);
        txtCorreo.setBackground(new java.awt.Color(0,0,0,1));
        txtCorreo.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(230, 231, 235));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCorreo.setText("Correo");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 210, 40));

        txtCedula.setEditable(false);
        txtCedula.setBackground(new java.awt.Color(0,0,0,1));
        txtCedula.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(230, 231, 235));
        txtCedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCedula.setText("Cédula");
        txtCedula.setBorder(null);
        txtCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedulaMousePressed(evt);
            }
        });
        add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 210, 40));

        txtSexo.setEditable(false);
        txtSexo.setBackground(new java.awt.Color(0,0,0,1));
        txtSexo.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtSexo.setForeground(new java.awt.Color(230, 231, 235));
        txtSexo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSexo.setText("Sexo");
        txtSexo.setBorder(null);
        txtSexo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSexoMousePressed(evt);
            }
        });
        add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 210, 40));

        txtEdad.setEditable(false);
        txtEdad.setBackground(new java.awt.Color(0,0,0,1));
        txtEdad.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(230, 231, 235));
        txtEdad.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEdad.setText("Edad");
        txtEdad.setBorder(null);
        txtEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEdadMousePressed(evt);
            }
        });
        add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 210, 40));

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(0,0,0,1));
        txtTelefono.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(230, 231, 235));
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelefono.setText("Teléfono");
        txtTelefono.setBorder(null);
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 210, 40));

        labelSsexo.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelSsexo.setForeground(new java.awt.Color(230, 231, 235));
        labelSsexo.setText("Sexo:");
        add(labelSsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        labelEdad.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelEdad.setForeground(new java.awt.Color(230, 231, 235));
        labelEdad.setText("Edad:");
        add(labelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        labelMunicipio.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelMunicipio.setForeground(new java.awt.Color(230, 231, 235));
        labelMunicipio.setText("Municipio:");
        add(labelMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        labelTelefono.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelTelefono.setForeground(new java.awt.Color(230, 231, 235));
        labelTelefono.setText("Telefono:");
        add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        labelCedula.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelCedula.setForeground(new java.awt.Color(230, 231, 235));
        labelCedula.setText("Cédula:");
        add(labelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        labelCorreo.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelCorreo.setForeground(new java.awt.Color(230, 231, 235));
        labelCorreo.setText("Correo:");
        add(labelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        labelApellido.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelApellido.setForeground(new java.awt.Color(230, 231, 235));
        labelApellido.setText("Apellidos:");
        add(labelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        labelNombre.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(230, 231, 235));
        labelNombre.setText("Nombres:");
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtMunicipio.setEditable(false);
        txtMunicipio.setBackground(new java.awt.Color(0,0,0,1));
        txtMunicipio.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtMunicipio.setForeground(new java.awt.Color(230, 231, 235));
        txtMunicipio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMunicipio.setText("Municipio");
        txtMunicipio.setBorder(null);
        txtMunicipio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMunicipioMousePressed(evt);
            }
        });
        add(txtMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 210, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
 
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMousePressed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_txtApellidoMousePressed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaMousePressed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void txtMunicipioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMunicipioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMunicipioMousePressed

    private void txtEdadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEdadMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadMousePressed

    private void txtSexoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSexoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelMunicipio;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSsexo;
    private javax.swing.JLabel labelTelefono;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txtMunicipio;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtSexo;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
