/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewprincipal;

/**
 *
 * @author Estefany Torres
 */
public class SistemaPrincipal extends javax.swing.JPanel {

    public SistemaPrincipal() {
        initComponents();
        labelPresionadoUsuario.setVisible(false);
        labelPresionadoReservacion.setVisible(false);
        labelPresionadoEmpleado.setVisible(false);
        labelPresionadoInventario.setVisible(false);
        labelPresionadoSalir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenuLateral = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        iconoSalir = new javax.swing.JLabel();
        labelPresionadoSalir = new javax.swing.JLabel();
        botonMenu = new javax.swing.JButton();
        iconoIMenu = new javax.swing.JLabel();
        labelPresionadoMenu = new javax.swing.JLabel();
        botonInventario = new javax.swing.JButton();
        iconoInventario = new javax.swing.JLabel();
        labelPresionadoInventario = new javax.swing.JLabel();
        botonEmpleados = new javax.swing.JButton();
        iconoEmpleados = new javax.swing.JLabel();
        labelPresionadoEmpleado = new javax.swing.JLabel();
        botonReservaciones = new javax.swing.JButton();
        iconoReservaciones = new javax.swing.JLabel();
        labelPresionadoReservacion = new javax.swing.JLabel();
        botonUsuario = new javax.swing.JButton();
        iconoUsuario = new javax.swing.JLabel();
        labelPresionadoUsuario = new javax.swing.JLabel();
        fondoMenuLateral = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();

        setBackground(new java.awt.Color(39, 45, 47));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenuLateral.setBackground(new java.awt.Color(39, 45, 47));
        panelMenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSalir.setBackground(new java.awt.Color(230, 231, 235));
        botonSalir.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        botonSalir.setToolTipText("Salir");
        botonSalir.setBorder(null);
        botonSalir.setBorderPainted(false);
        botonSalir.setContentAreaFilled(false);
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalirMouseEntered(evt);
            }
        });
        panelMenuLateral.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 650, 80, 44));

        iconoSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewprincipal/iconSalir.png"))); // NOI18N
        panelMenuLateral.add(iconoSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 650, 44, 45));

        labelPresionadoSalir.setBackground(new java.awt.Color(39, 45, 47));
        labelPresionadoSalir.setForeground(new java.awt.Color(39, 45, 47));
        labelPresionadoSalir.setOpaque(true);
        panelMenuLateral.add(labelPresionadoSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 643, 84, 60));

        botonMenu.setBackground(new java.awt.Color(230, 231, 235));
        botonMenu.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        botonMenu.setToolTipText("Inventario");
        botonMenu.setBorder(null);
        botonMenu.setBorderPainted(false);
        botonMenu.setContentAreaFilled(false);
        botonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMenuMouseEntered(evt);
            }
        });
        panelMenuLateral.add(botonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 80, 44));

        iconoIMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoIMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewprincipal/iconMenu.png"))); // NOI18N
        panelMenuLateral.add(iconoIMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 410, 44, 45));

        labelPresionadoMenu.setBackground(new java.awt.Color(39, 45, 47));
        labelPresionadoMenu.setForeground(new java.awt.Color(39, 45, 47));
        labelPresionadoMenu.setOpaque(true);
        panelMenuLateral.add(labelPresionadoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 84, 60));

        botonInventario.setBackground(new java.awt.Color(230, 231, 235));
        botonInventario.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        botonInventario.setToolTipText("Inventario");
        botonInventario.setBorder(null);
        botonInventario.setBorderPainted(false);
        botonInventario.setContentAreaFilled(false);
        botonInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonInventarioMouseEntered(evt);
            }
        });
        panelMenuLateral.add(botonInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 80, 44));

        iconoInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewprincipal/iconInventario.png"))); // NOI18N
        panelMenuLateral.add(iconoInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 350, 44, 45));

        labelPresionadoInventario.setBackground(new java.awt.Color(39, 45, 47));
        labelPresionadoInventario.setForeground(new java.awt.Color(39, 45, 47));
        labelPresionadoInventario.setOpaque(true);
        panelMenuLateral.add(labelPresionadoInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 343, 84, 60));

        botonEmpleados.setBackground(new java.awt.Color(230, 231, 235));
        botonEmpleados.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        botonEmpleados.setToolTipText("Empleados");
        botonEmpleados.setBorder(null);
        botonEmpleados.setBorderPainted(false);
        botonEmpleados.setContentAreaFilled(false);
        botonEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEmpleadosMouseEntered(evt);
            }
        });
        panelMenuLateral.add(botonEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 80, 50));

        iconoEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewprincipal/iconEmpleados.png"))); // NOI18N
        panelMenuLateral.add(iconoEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 290, 44, 45));

        labelPresionadoEmpleado.setBackground(new java.awt.Color(39, 45, 47));
        labelPresionadoEmpleado.setForeground(new java.awt.Color(39, 45, 47));
        labelPresionadoEmpleado.setOpaque(true);
        panelMenuLateral.add(labelPresionadoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 283, 84, 60));

        botonReservaciones.setBackground(new java.awt.Color(230, 231, 235));
        botonReservaciones.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        botonReservaciones.setToolTipText("Reservaciones");
        botonReservaciones.setBorder(null);
        botonReservaciones.setBorderPainted(false);
        botonReservaciones.setContentAreaFilled(false);
        botonReservaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonReservaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonReservacionesMouseEntered(evt);
            }
        });
        panelMenuLateral.add(botonReservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 230, 80, 50));

        iconoReservaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoReservaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewprincipal/iconReservaciones.png"))); // NOI18N
        panelMenuLateral.add(iconoReservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 230, 44, 45));

        labelPresionadoReservacion.setBackground(new java.awt.Color(39, 45, 47));
        labelPresionadoReservacion.setForeground(new java.awt.Color(39, 45, 47));
        labelPresionadoReservacion.setOpaque(true);
        panelMenuLateral.add(labelPresionadoReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 223, 84, 60));

        botonUsuario.setBackground(new java.awt.Color(230, 231, 235));
        botonUsuario.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        botonUsuario.setToolTipText("Perfil");
        botonUsuario.setBorder(null);
        botonUsuario.setBorderPainted(false);
        botonUsuario.setContentAreaFilled(false);
        botonUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonUsuarioMouseEntered(evt);
            }
        });
        panelMenuLateral.add(botonUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, 80, 44));

        iconoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewprincipal/iconUsuario.png"))); // NOI18N
        panelMenuLateral.add(iconoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 40, 44, 50));

        labelPresionadoUsuario.setBackground(new java.awt.Color(39, 45, 47));
        labelPresionadoUsuario.setForeground(new java.awt.Color(39, 45, 47));
        labelPresionadoUsuario.setOpaque(true);
        panelMenuLateral.add(labelPresionadoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 84, 60));

        fondoMenuLateral.setBackground(new java.awt.Color(39, 45, 47));
        fondoMenuLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewprincipal/fondoMenuLateral.png"))); // NOI18N
        panelMenuLateral.add(fondoMenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 84, 720));

        add(panelMenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 84, 720));

        panelPrincipal.setBackground(new java.awt.Color(39, 45, 47));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 0, 926, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void botonUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonUsuarioMouseEntered
        // TODO add your handling code here:
        labelPresionadoUsuario.setVisible(true);
        labelPresionadoReservacion.setVisible(false);
        labelPresionadoEmpleado.setVisible(false);
        labelPresionadoInventario.setVisible(false);
        labelPresionadoMenu.setVisible(false);
        labelPresionadoSalir.setVisible(false);
    }//GEN-LAST:event_botonUsuarioMouseEntered

    private void botonReservacionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReservacionesMouseEntered
        // TODO add your handling code here:
        labelPresionadoUsuario.setVisible(false);
        labelPresionadoReservacion.setVisible(true);
        labelPresionadoEmpleado.setVisible(false);
        labelPresionadoInventario.setVisible(false);
        labelPresionadoMenu.setVisible(false);
        labelPresionadoSalir.setVisible(false);
    }//GEN-LAST:event_botonReservacionesMouseEntered

    private void botonEmpleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEmpleadosMouseEntered
        // TODO add your handling code here:
        labelPresionadoUsuario.setVisible(false);
        labelPresionadoReservacion.setVisible(false);
        labelPresionadoEmpleado.setVisible(true);
        labelPresionadoInventario.setVisible(false);
        labelPresionadoMenu.setVisible(false);
        labelPresionadoSalir.setVisible(false);
    }//GEN-LAST:event_botonEmpleadosMouseEntered

    private void botonInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInventarioMouseEntered
        // TODO add your handling code here:
        labelPresionadoUsuario.setVisible(false);
        labelPresionadoReservacion.setVisible(false);
        labelPresionadoEmpleado.setVisible(false);
        labelPresionadoInventario.setVisible(true);
        labelPresionadoMenu.setVisible(false);
        labelPresionadoSalir.setVisible(false);
    }//GEN-LAST:event_botonInventarioMouseEntered

    private void botonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseEntered
        // TODO add your handling code here:
        labelPresionadoUsuario.setVisible(false);
        labelPresionadoReservacion.setVisible(false);
        labelPresionadoEmpleado.setVisible(false);
        labelPresionadoInventario.setVisible(false);
        labelPresionadoMenu.setVisible(false);
        labelPresionadoSalir.setVisible(true);
    }//GEN-LAST:event_botonSalirMouseEntered

    private void botonMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuMouseEntered
        // TODO add your handling code here:
        labelPresionadoUsuario.setVisible(false);
        labelPresionadoReservacion.setVisible(false);
        labelPresionadoEmpleado.setVisible(false);
        labelPresionadoInventario.setVisible(false);
        labelPresionadoMenu.setVisible(true);
        labelPresionadoSalir.setVisible(false);
    }//GEN-LAST:event_botonMenuMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonEmpleados;
    public javax.swing.JButton botonInventario;
    public javax.swing.JButton botonMenu;
    public javax.swing.JButton botonReservaciones;
    public javax.swing.JButton botonSalir;
    public javax.swing.JButton botonUsuario;
    private javax.swing.JLabel fondoMenuLateral;
    public javax.swing.JLabel iconoEmpleados;
    public javax.swing.JLabel iconoIMenu;
    public javax.swing.JLabel iconoInventario;
    public javax.swing.JLabel iconoReservaciones;
    private javax.swing.JLabel iconoSalir;
    private javax.swing.JLabel iconoUsuario;
    private javax.swing.JLabel labelPresionadoEmpleado;
    private javax.swing.JLabel labelPresionadoInventario;
    private javax.swing.JLabel labelPresionadoMenu;
    private javax.swing.JLabel labelPresionadoReservacion;
    private javax.swing.JLabel labelPresionadoSalir;
    private javax.swing.JLabel labelPresionadoUsuario;
    public javax.swing.JPanel panelMenuLateral;
    public javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
