/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewinventario;

import java.awt.Color;

/**
 *
 * @author emmez
 */
public class PanelIngresarProveedor extends javax.swing.JPanel {

    /**
     * Creates new form PanelIngresarProveedor
     */
    public PanelIngresarProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegresarI = new javax.swing.JButton();
        fondoBotonRegresar = new javax.swing.JLabel();
        labelTItulo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        labelInputCorreo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        labelInputNombre = new javax.swing.JLabel();
        txtRIF = new javax.swing.JTextField();
        labelInputRIF = new javax.swing.JLabel();
        comboBoxMunicipio = new javax.swing.JComboBox<>();
        labelInputMunicipio = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        labelInputTelefono = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JButton();
        fondoBotonRegistrar = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        fondoTItulo = new javax.swing.JLabel();
        fondoPanel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(39, 45, 47));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRegresarI.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonRegresarI.setForeground(new java.awt.Color(230, 231, 235));
        botonRegresarI.setBorder(null);
        botonRegresarI.setBorderPainted(false);
        botonRegresarI.setContentAreaFilled(false);
        botonRegresarI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresarI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegresarI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresarIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresarIMouseExited(evt);
            }
        });
        add(botonRegresarI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 50, 50));

        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonRegresar.png"))); // NOI18N
        add(fondoBotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 50));

        labelTItulo.setBackground(new java.awt.Color(0, 0, 0));
        labelTItulo.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        labelTItulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTItulo.setText("DATOS DEL PROVEEDOR");
        add(labelTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 320, 30));

        txtCorreo.setBackground(new java.awt.Color(0,0,0,1));
        txtCorreo.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtCorreo.setForeground(java.awt.Color.lightGray);
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCorreo.setText("Correo");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 360, 40));

        labelInputCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/inputGrandeProveedor.png"))); // NOI18N
        add(labelInputCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        txtNombre.setBackground(new java.awt.Color(0,0,0,1));
        txtNombre.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtNombre.setForeground(java.awt.Color.lightGray);
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setText("Nombre del Proveedor");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 160, 40));

        labelInputNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/inputPequenoProveedor.png"))); // NOI18N
        add(labelInputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        txtRIF.setBackground(new java.awt.Color(0,0,0,1));
        txtRIF.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtRIF.setForeground(java.awt.Color.lightGray);
        txtRIF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRIF.setText("RIF");
        txtRIF.setBorder(null);
        txtRIF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtRIFMousePressed(evt);
            }
        });
        add(txtRIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 160, 40));

        labelInputRIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/inputPequenoProveedor.png"))); // NOI18N
        add(labelInputRIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        comboBoxMunicipio.setBackground(new java.awt.Color(86, 92, 94));
        comboBoxMunicipio.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        comboBoxMunicipio.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el municipio", "Baruta", "Chacao", "El Hatillo", "Libertador", "Sucre" }));
        comboBoxMunicipio.setBorder(null);
        comboBoxMunicipio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comboBoxMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 360, 40));

        labelInputMunicipio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/inputGrandeProveedor.png"))); // NOI18N
        add(labelInputMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        txtTelefono.setBackground(new java.awt.Color(0,0,0,1));
        txtTelefono.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtTelefono.setForeground(java.awt.Color.lightGray);
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelefono.setText("Teléfono");
        txtTelefono.setBorder(null);
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 360, 40));

        labelInputTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/inputGrandeProveedor.png"))); // NOI18N
        add(labelInputTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, -1));

        botonRegistrar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(39, 45, 47));
        botonRegistrar.setText("Registrar");
        botonRegistrar.setBorder(null);
        botonRegistrar.setBorderPainted(false);
        botonRegistrar.setContentAreaFilled(false);
        botonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseExited(evt);
            }
        });
        add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 140, 60));

        fondoBotonRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoBotonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonRegistrarProveedor.png"))); // NOI18N
        add(fondoBotonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 160, 60));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/imagenIngresarProveedor.png"))); // NOI18N
        add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        fondoTItulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/fondoTItuloDatosProveedor.png"))); // NOI18N
        add(fondoTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        fondoPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/fondoIngresarProveedor.png"))); // NOI18N
        add(fondoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarIMouseEntered
        // TODO add your handling code here:
        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonRegresarPresionado.png"))); // NOI18N
    }//GEN-LAST:event_botonRegresarIMouseEntered

    private void botonRegresarIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarIMouseExited
        // TODO add your handling code here:
        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonRegresar.png"))); // NOI18N
    }//GEN-LAST:event_botonRegresarIMouseExited

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
        if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Nombre del Proveedor");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }

        if(txtRIF.getText().isEmpty()){
            txtRIF.setText("RIF");
            txtRIF.setForeground(Color.LIGHT_GRAY);
        }

        if(txtCorreo.getText().equals("Correo")){
            txtCorreo.setText("");
            txtCorreo.setForeground(new Color(230,231,235));
        }

        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Teléfono");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        // TODO add your handling code here:
        if(txtNombre.getText().equals("Nombre del Proveedor")){
            txtNombre.setText("");
            txtNombre.setForeground(new Color(230,231,235));
        }

        if(txtRIF.getText().isEmpty()){
            txtRIF.setText("RIF");
            txtRIF.setForeground(Color.LIGHT_GRAY);
        }

        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(Color.LIGHT_GRAY);
        }

        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Teléfono");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtRIFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRIFMousePressed
        // TODO add your handling code here:
        if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Nombre del Proveedor");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }

        if(txtRIF.getText().equals("RIF")){
            txtRIF.setText("");
            txtRIF.setForeground(new Color(230,231,235));
        }

        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(Color.LIGHT_GRAY);
        }

        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Teléfono");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtRIFMousePressed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        // TODO add your handling code here:
        if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Nombre del Proveedor");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }

        if(txtRIF.getText().isEmpty()){
            txtRIF.setText("RIF");
            txtRIF.setForeground(Color.LIGHT_GRAY);
        }

        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(Color.LIGHT_GRAY);
        }

        if(txtTelefono.getText().equals("Teléfono")){
            txtTelefono.setText("");
            txtTelefono.setForeground(new Color(230,231,235));
        }
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void botonRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseEntered
        // TODO add your handling code here:
        fondoBotonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonRegistrarProveedorPresionado.png")));
    }//GEN-LAST:event_botonRegistrarMouseEntered

    private void botonRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseExited
        // TODO add your handling code here:
        fondoBotonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonRegistrarProveedor.png")));
    }//GEN-LAST:event_botonRegistrarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonRegistrar;
    public javax.swing.JButton botonRegresarI;
    public javax.swing.JComboBox<String> comboBoxMunicipio;
    private javax.swing.JLabel fondoBotonRegistrar;
    private javax.swing.JLabel fondoBotonRegresar;
    private javax.swing.JLabel fondoPanel;
    private javax.swing.JLabel fondoTItulo;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel labelInputCorreo;
    private javax.swing.JLabel labelInputMunicipio;
    private javax.swing.JLabel labelInputNombre;
    private javax.swing.JLabel labelInputRIF;
    private javax.swing.JLabel labelInputTelefono;
    public javax.swing.JLabel labelTItulo;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtRIF;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
