/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewinventario;

/**
 *
 * @author Estefany Torres
 */
public class PanelInsumo extends javax.swing.JPanel {

    public PanelInsumo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonVerInsumo = new javax.swing.JButton();
        labelCantidad = new javax.swing.JLabel();
        labelNombreInsumo = new javax.swing.JLabel();
        fondoInsumo = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        labelBotonVer = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 0));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonVerInsumo.setFont(new java.awt.Font("Open Sans SemiBold", 0, 16)); // NOI18N
        botonVerInsumo.setForeground(new java.awt.Color(230, 231, 235));
        botonVerInsumo.setBorder(null);
        botonVerInsumo.setBorderPainted(false);
        botonVerInsumo.setContentAreaFilled(false);
        botonVerInsumo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerInsumo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(botonVerInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 30, 40));

        labelCantidad.setFont(new java.awt.Font("Open Sans Medium", 0, 16)); // NOI18N
        labelCantidad.setForeground(new java.awt.Color(230, 231, 235));
        labelCantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCantidad.setText("0");
        add(labelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 80, 20));

        labelNombreInsumo.setFont(new java.awt.Font("Open Sans Medium", 0, 16)); // NOI18N
        labelNombreInsumo.setForeground(new java.awt.Color(230, 231, 235));
        labelNombreInsumo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNombreInsumo.setText("Insumo");
        add(labelNombreInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 190, 30));

        fondoInsumo.setBackground(new java.awt.Color(102, 102, 102));
        fondoInsumo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoInsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/fondoNombreInsumo.png"))); // NOI18N
        add(fondoInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 280, 60));
        add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        labelBotonVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonVer.png"))); // NOI18N
        add(labelBotonVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 27, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonVerInsumo;
    private javax.swing.JLabel fondoInsumo;
    private javax.swing.JLabel labelBotonVer;
    public javax.swing.JLabel labelCantidad;
    public javax.swing.JLabel labelID;
    public javax.swing.JLabel labelNombreInsumo;
    // End of variables declaration//GEN-END:variables
}
