/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewinventario;

/**
 *
 * @author Estefany Torres
 */
public class PanelSalida extends javax.swing.JPanel {

    public PanelSalida() {
        initComponents();
        fondoSalidaPresionado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSalida = new javax.swing.JButton();
        labelIconoSalida = new javax.swing.JLabel();
        labelFechaSalida = new javax.swing.JLabel();
        fondoSalidaPresionado = new javax.swing.JLabel();
        fondoSalida = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 0));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSalida.setFont(new java.awt.Font("Open Sans SemiBold", 0, 16)); // NOI18N
        botonSalida.setForeground(new java.awt.Color(230, 231, 235));
        botonSalida.setBorder(null);
        botonSalida.setBorderPainted(false);
        botonSalida.setContentAreaFilled(false);
        botonSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSalidaMouseExited(evt);
            }
        });
        add(botonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 210, 50));

        labelIconoSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/iconoSalida.png"))); // NOI18N
        add(labelIconoSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 26, -1, -1));

        labelFechaSalida.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        labelFechaSalida.setForeground(new java.awt.Color(230, 231, 235));
        labelFechaSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechaSalida.setText("03/07/23 16:00");
        add(labelFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 150, 40));

        fondoSalidaPresionado.setBackground(new java.awt.Color(102, 102, 102));
        fondoSalidaPresionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoSalidaPresionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/fondoNombreEyS.png"))); // NOI18N
        add(fondoSalidaPresionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 10, 220, 60));

        fondoSalida.setBackground(new java.awt.Color(102, 102, 102));
        fondoSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/fondoNombreEyS.png"))); // NOI18N
        add(fondoSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 10, 220, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalidaMouseEntered
        // TODO add your handling code here:
        fondoSalidaPresionado.setVisible(true);
    }//GEN-LAST:event_botonSalidaMouseEntered

    private void botonSalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalidaMouseExited
        // TODO add your handling code here:
        fondoSalidaPresionado.setVisible(false);
    }//GEN-LAST:event_botonSalidaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonSalida;
    private javax.swing.JLabel fondoSalida;
    private javax.swing.JLabel fondoSalidaPresionado;
    public javax.swing.JLabel labelFechaSalida;
    private javax.swing.JLabel labelIconoSalida;
    // End of variables declaration//GEN-END:variables
}
