/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewinventario;

/**
 *
 * @author Estefany Torres
 */
public class PanelProveedor extends javax.swing.JPanel {

    public PanelProveedor() {
        initComponents();
        fondoProveedorPresionado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonProveedor = new javax.swing.JButton();
        labelIconoProveedor = new javax.swing.JLabel();
        labelNombreProveedor = new javax.swing.JLabel();
        fondoProveedorPresionado = new javax.swing.JLabel();
        fondoProveedor = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 0));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonProveedor.setFont(new java.awt.Font("Open Sans SemiBold", 0, 16)); // NOI18N
        botonProveedor.setForeground(new java.awt.Color(230, 231, 235));
        botonProveedor.setBorder(null);
        botonProveedor.setBorderPainted(false);
        botonProveedor.setContentAreaFilled(false);
        botonProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonProveedorMouseExited(evt);
            }
        });
        add(botonProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 60));

        labelIconoProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/iconoProveedor.png"))); // NOI18N
        add(labelIconoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        labelNombreProveedor.setFont(new java.awt.Font("Open Sans Medium", 0, 16)); // NOI18N
        labelNombreProveedor.setForeground(new java.awt.Color(230, 231, 235));
        labelNombreProveedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNombreProveedor.setText("Insumo");
        add(labelNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 180, 40));

        fondoProveedorPresionado.setBackground(new java.awt.Color(102, 102, 102));
        fondoProveedorPresionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoProveedorPresionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/fondoNombreProveedor.png"))); // NOI18N
        add(fondoProveedorPresionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 60));

        fondoProveedor.setBackground(new java.awt.Color(102, 102, 102));
        fondoProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/fondoNombreProveedor.png"))); // NOI18N
        add(fondoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void botonProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProveedorMouseEntered
        // TODO add your handling code here:
        fondoProveedorPresionado.setVisible(true);
    }//GEN-LAST:event_botonProveedorMouseEntered

    private void botonProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProveedorMouseExited
        // TODO add your handling code here:
        fondoProveedorPresionado.setVisible(false);
    }//GEN-LAST:event_botonProveedorMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonProveedor;
    private javax.swing.JLabel fondoProveedor;
    private javax.swing.JLabel fondoProveedorPresionado;
    private javax.swing.JLabel labelIconoProveedor;
    public javax.swing.JLabel labelNombreProveedor;
    // End of variables declaration//GEN-END:variables
}
