/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewinventario;

import java.awt.GridLayout;

/**
 *
 * @author emmez
 */
public class PanelConsultarLotes extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsultarNominas
     */
    public PanelConsultarLotes() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResponsable = new javax.swing.JLabel();
        labelResponsable = new javax.swing.JLabel();
        jScrollPaneRegistros = new javax.swing.JScrollPane();
        tablaRegistros = new javax.swing.JTable();
        labelBuscar = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        panelRegistros = new javax.swing.JPanel(new GridLayout(0, 1, 1, 1));
        labelPanelNominas = new javax.swing.JLabel();
        labelTItulo = new javax.swing.JLabel();
        labelFondoTItulo = new javax.swing.JLabel();
        botonRegresarS = new javax.swing.JButton();
        botonRegresarE = new javax.swing.JButton();
        fondoBotonRegresar = new javax.swing.JLabel();
        jDateFiltro = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(39, 45, 47));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResponsable.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        txtResponsable.setForeground(new java.awt.Color(230, 231, 235));
        txtResponsable.setText("Italo Visconti");
        add(txtResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 220, 50));

        labelResponsable.setBackground(new java.awt.Color(0, 0, 0));
        labelResponsable.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        labelResponsable.setForeground(new java.awt.Color(230, 231, 235));
        labelResponsable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelResponsable.setText("Responsable");
        add(labelResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 130, 50));

        tablaRegistros.setBackground(new java.awt.Color(230, 231, 235));
        tablaRegistros.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        tablaRegistros.setForeground(new java.awt.Color(39, 45, 47));
        tablaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tipo", "Unidad", "Cantidad", "Fecha de Vencimiento", "Responsable"
            }
        ));
        jScrollPaneRegistros.setViewportView(tablaRegistros);

        add(jScrollPaneRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 578, 552));

        labelBuscar.setFont(new java.awt.Font("Open Sans Medium", 0, 16)); // NOI18N
        labelBuscar.setForeground(new java.awt.Color(230, 231, 235));
        labelBuscar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelBuscar.setText("Buscar por");
        add(labelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 130, -1));

        jScrollPane.setBorder(null);
        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane.setViewportView(null);

        panelRegistros.setBackground(new java.awt.Color(58, 64, 65));
        jScrollPane.setViewportView(panelRegistros);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 186, 246, 470));

        labelPanelNominas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/panelNominas.png"))); // NOI18N
        add(labelPanelNominas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 250, 500));

        labelTItulo.setBackground(new java.awt.Color(0, 0, 0));
        labelTItulo.setFont(new java.awt.Font("Open Sans Medium", 1, 16)); // NOI18N
        labelTItulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTItulo.setText("ENTRADAS");
        add(labelTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 250, 50));

        labelFondoTItulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/fondoTituloNomina.png"))); // NOI18N
        add(labelFondoTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        botonRegresarS.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonRegresarS.setForeground(new java.awt.Color(230, 231, 235));
        botonRegresarS.setBorder(null);
        botonRegresarS.setBorderPainted(false);
        botonRegresarS.setContentAreaFilled(false);
        botonRegresarS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresarS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegresarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresarSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresarSMouseExited(evt);
            }
        });
        add(botonRegresarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 50, 50));

        botonRegresarE.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonRegresarE.setForeground(new java.awt.Color(230, 231, 235));
        botonRegresarE.setBorder(null);
        botonRegresarE.setBorderPainted(false);
        botonRegresarE.setContentAreaFilled(false);
        botonRegresarE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresarE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegresarE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresarEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresarEMouseExited(evt);
            }
        });
        add(botonRegresarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 50, 50));

        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonRegresar.png"))); // NOI18N
        add(fondoBotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 50));

        jDateFiltro.setFont(new java.awt.Font("Open Sans Medium", 0, 13)); // NOI18N
        add(jDateFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 260, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarEMouseEntered
        // TODO add your handling code here:
        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonRegresarPresionado.png"))); // NOI18N
    }//GEN-LAST:event_botonRegresarEMouseEntered

    private void botonRegresarEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarEMouseExited
        // TODO add your handling code here:
        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonRegresar.png"))); // NOI18N
    }//GEN-LAST:event_botonRegresarEMouseExited

    private void botonRegresarSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarSMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarSMouseEntered

    private void botonRegresarSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarSMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarSMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonRegresarE;
    public javax.swing.JButton botonRegresarS;
    private javax.swing.JLabel fondoBotonRegresar;
    public com.toedter.calendar.JDateChooser jDateFiltro;
    public javax.swing.JScrollPane jScrollPane;
    public javax.swing.JScrollPane jScrollPaneRegistros;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelFondoTItulo;
    private javax.swing.JLabel labelPanelNominas;
    public javax.swing.JLabel labelResponsable;
    public javax.swing.JLabel labelTItulo;
    public javax.swing.JPanel panelRegistros;
    public javax.swing.JTable tablaRegistros;
    public javax.swing.JLabel txtResponsable;
    // End of variables declaration//GEN-END:variables
}
