/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewinventario;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import model.modelview.MyComboBoxRender;

/**
 *
 * @author Estefany Torres
 */
public class PanelIngresarInsumo extends javax.swing.JPanel {

    public PanelIngresarInsumo() {
        initComponents();
        comboBoxTipoInsumo.setOpaque(false);
        comboBoxTipoInsumo.setEditable(true);
        JTextField boxField = (JTextField)comboBoxTipoInsumo .getEditor().getEditorComponent();
        boxField.setBorder(BorderFactory.createEmptyBorder());
        boxField.setForeground(new Color(230,231,235));
        boxField.setBackground(new Color(0, 0, 0, 0));
        boxField.setFocusable(false);
        comboBoxTipoInsumo.setRenderer(new MyComboBoxRender());
        
        comboBoxUnidad.setOpaque(false);
        comboBoxUnidad.setEditable(true);
        boxField = (JTextField)comboBoxUnidad .getEditor().getEditorComponent();
        boxField.setBorder(BorderFactory.createEmptyBorder());
        boxField.setForeground(new Color(230,231,235));
        boxField.setBackground(new Color(0, 0, 0, 0));
        boxField.setFocusable(false);
        comboBoxUnidad.setRenderer(new MyComboBoxRender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegistrar = new javax.swing.JButton();
        fondoBotonRegistrar = new javax.swing.JLabel();
        comboBoxProveedor = new javax.swing.JComboBox<>();
        inputProveedor = new javax.swing.JLabel();
        comboBoxUnidad = new javax.swing.JComboBox<>();
        inputUnidadInsumo = new javax.swing.JLabel();
        comboBoxTipoInsumo = new javax.swing.JComboBox<>();
        inputTipoInsumo = new javax.swing.JLabel();
        txtNombreInsumo = new javax.swing.JTextField();
        inputNombre = new javax.swing.JLabel();
        labelTItulo = new javax.swing.JLabel();
        labelFondoITitulo = new javax.swing.JLabel();
        labelFondoIngresar = new javax.swing.JLabel();
        botonRegresarI = new javax.swing.JButton();
        fondoBotonRegresar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(39, 45, 47));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRegistrar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(39, 45, 47));
        botonRegistrar.setText("Registrar");
        botonRegistrar.setBorder(null);
        botonRegistrar.setBorderPainted(false);
        botonRegistrar.setContentAreaFilled(false);
        botonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseExited(evt);
            }
        });
        add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 145, 50));

        fondoBotonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonRegistrar.png"))); // NOI18N
        add(fondoBotonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));

        comboBoxProveedor.setBackground(new java.awt.Color(86, 92, 94));
        comboBoxProveedor.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        comboBoxProveedor.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Proveedor", "Kilogramo", "Botella", "Litro" }));
        comboBoxProveedor.setBorder(null);
        comboBoxProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comboBoxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 260, 40));

        inputProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/inputDatosInsumo.png"))); // NOI18N
        add(inputProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 280, 40));

        comboBoxUnidad.setBackground(new java.awt.Color(86, 92, 94));
        comboBoxUnidad.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        comboBoxUnidad.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona unidad", "Kilogramo", "Botella", "Litro" }));
        comboBoxUnidad.setBorder(null);
        comboBoxUnidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comboBoxUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 260, 40));

        inputUnidadInsumo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputUnidadInsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/inputDatosInsumo.png"))); // NOI18N
        add(inputUnidadInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 280, 40));

        comboBoxTipoInsumo.setBackground(new java.awt.Color(86, 92, 94));
        comboBoxTipoInsumo.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        comboBoxTipoInsumo.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxTipoInsumo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona tipo de insumo", "Carnes", "Frutas", "Vegetales", "Bebidas", "Otros" }));
        comboBoxTipoInsumo.setBorder(null);
        comboBoxTipoInsumo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comboBoxTipoInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 260, 40));

        inputTipoInsumo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputTipoInsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/inputDatosInsumo.png"))); // NOI18N
        add(inputTipoInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 280, 40));

        txtNombreInsumo.setBackground(new java.awt.Color(0,0,0,1));
        txtNombreInsumo.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtNombreInsumo.setForeground(java.awt.Color.lightGray);
        txtNombreInsumo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombreInsumo.setText("Nombre");
        txtNombreInsumo.setBorder(null);
        txtNombreInsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreInsumoMousePressed(evt);
            }
        });
        add(txtNombreInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 260, 40));

        inputNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/inputDatosInsumo.png"))); // NOI18N
        add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 280, 40));

        labelTItulo.setBackground(new java.awt.Color(0, 0, 0));
        labelTItulo.setFont(new java.awt.Font("Open Sans Medium", 1, 16)); // NOI18N
        labelTItulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTItulo.setText("DATOS DEL INSUMO");
        add(labelTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 340, 50));

        labelFondoITitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/fondoTituloDatos.png"))); // NOI18N
        add(labelFondoITitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        labelFondoIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/fondoIngresarDatos.png"))); // NOI18N
        add(labelFondoIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 340, 470));

        botonRegresarI.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonRegresarI.setForeground(new java.awt.Color(230, 231, 235));
        botonRegresarI.setBorder(null);
        botonRegresarI.setBorderPainted(false);
        botonRegresarI.setContentAreaFilled(false);
        botonRegresarI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresarI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegresarI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresarIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresarIMouseExited(evt);
            }
        });
        add(botonRegresarI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 50, 50));

        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonRegresar.png"))); // NOI18N
        add(fondoBotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreInsumoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreInsumoMousePressed
        // TODO add your handling code here:
        if(txtNombreInsumo.getText().equals("Nombre")){
            txtNombreInsumo.setText("");
            txtNombreInsumo.setForeground(new Color(230,231,235));
        }
    }//GEN-LAST:event_txtNombreInsumoMousePressed

    private void botonRegresarIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarIMouseEntered
        // TODO add your handling code here:
        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonRegresarPresionado.png"))); // NOI18N
    }//GEN-LAST:event_botonRegresarIMouseEntered

    private void botonRegresarIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarIMouseExited
        // TODO add your handling code here:
        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonRegresar.png"))); // NOI18N
    }//GEN-LAST:event_botonRegresarIMouseExited

    private void botonRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseEntered
        // TODO add your handling code here:
        fondoBotonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonRegistrarPresionado.png"))); // NOI18N
    }//GEN-LAST:event_botonRegistrarMouseEntered

    private void botonRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseExited
        // TODO add your handling code here:
        fondoBotonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonRegistrar.png"))); // NOI18N
    }//GEN-LAST:event_botonRegistrarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonRegistrar;
    public javax.swing.JButton botonRegresarI;
    public javax.swing.JComboBox<String> comboBoxProveedor;
    public javax.swing.JComboBox<String> comboBoxTipoInsumo;
    public javax.swing.JComboBox<String> comboBoxUnidad;
    private javax.swing.JLabel fondoBotonRegistrar;
    private javax.swing.JLabel fondoBotonRegresar;
    private javax.swing.JLabel inputNombre;
    private javax.swing.JLabel inputProveedor;
    private javax.swing.JLabel inputTipoInsumo;
    private javax.swing.JLabel inputUnidadInsumo;
    private javax.swing.JLabel labelFondoITitulo;
    private javax.swing.JLabel labelFondoIngresar;
    public javax.swing.JLabel labelTItulo;
    public javax.swing.JTextField txtNombreInsumo;
    // End of variables declaration//GEN-END:variables
}
