/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewinventario;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import model.modelview.MyComboBoxRender;
import java.awt.GridLayout;

/**
 *
 * @author Estefany Torres
 */
public class PanelConsultarInventario extends javax.swing.JPanel {

    public PanelConsultarInventario() {
        initComponents();
        
        comboBoxTipoInsumo.setOpaque(false);
        comboBoxTipoInsumo.setEditable(true);
        JTextField boxField = (JTextField)comboBoxTipoInsumo .getEditor().getEditorComponent();
        boxField.setBorder(BorderFactory.createEmptyBorder());
        boxField.setForeground(new Color(39,45,47));
        boxField.setBackground(new Color(0, 0, 0, 0));
        boxField.setFocusable(false);
        comboBoxTipoInsumo.setRenderer(new MyComboBoxRender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTItulo = new javax.swing.JLabel();
        comboBoxTipoInsumo = new javax.swing.JComboBox<>();
        fondoComboInsumo = new javax.swing.JLabel();
        labelTItuloV = new javax.swing.JLabel();
        fondoTituloV = new javax.swing.JLabel();
        jScrollPaneV = new javax.swing.JScrollPane();
        panelInsumosVencidos = new javax.swing.JPanel(new GridLayout(0, 1, 1, 1));
        fondoPanelInsumosV = new javax.swing.JLabel();
        labelTItuloPR = new javax.swing.JLabel();
        fondoTituloPR = new javax.swing.JLabel();
        jScrollPanePR = new javax.swing.JScrollPane();
        panelInsumosPorReponer = new javax.swing.JPanel(new GridLayout(0, 1, 1, 1));
        fondoPanelInsumosPR = new javax.swing.JLabel();
        labelTItuloD = new javax.swing.JLabel();
        fondoTituloD = new javax.swing.JLabel();
        jScrollPaneD = new javax.swing.JScrollPane();
        panelInsumosDisponibles = new javax.swing.JPanel(new GridLayout(0, 1, 1, 1));
        fondoPanelInsumosD = new javax.swing.JLabel();
        botonAdvertencia = new javax.swing.JButton();
        fondoBotonAdvertencia = new javax.swing.JLabel();
        botonProveedor = new javax.swing.JButton();
        fondoBotonProveedor = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        fondoBotonBuscar = new javax.swing.JLabel();
        botonSalida = new javax.swing.JButton();
        fondoBotonSalida = new javax.swing.JLabel();
        botonEntrada = new javax.swing.JButton();
        fondoBotonEntrada = new javax.swing.JLabel();
        botonIngresar = new javax.swing.JButton();
        fondoBotonIngresar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(39, 45, 47));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTItulo.setBackground(new java.awt.Color(0, 0, 0));
        labelTItulo.setFont(new java.awt.Font("Open Sans", 1, 28)); // NOI18N
        labelTItulo.setForeground(new java.awt.Color(230, 231, 235));
        labelTItulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTItulo.setText("Inventario");
        add(labelTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 310, 50));

        comboBoxTipoInsumo.setBackground(new java.awt.Color(86, 92, 94));
        comboBoxTipoInsumo.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        comboBoxTipoInsumo.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxTipoInsumo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carnes", "Frutas", "Vegetales", "Bebidas", "Otros" }));
        comboBoxTipoInsumo.setBorder(null);
        comboBoxTipoInsumo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comboBoxTipoInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 48, 260, 35));

        fondoComboInsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoComboUsuario.png"))); // NOI18N
        add(fondoComboInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 310, 50));

        labelTItuloV.setBackground(new java.awt.Color(0, 0, 0));
        labelTItuloV.setFont(new java.awt.Font("Open Sans Medium", 1, 16)); // NOI18N
        labelTItuloV.setForeground(new java.awt.Color(230, 231, 235));
        labelTItuloV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTItuloV.setText("INSUMOS VENCIDOS");
        add(labelTItuloV, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 340, 50));

        fondoTituloV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/fondoTitulo2.png"))); // NOI18N
        add(fondoTituloV, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        jScrollPaneV.setBorder(null);
        jScrollPaneV.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneV.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPaneV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPaneV.setViewportView(panelInsumosDisponibles);

        panelInsumosVencidos.setBackground(new java.awt.Color(58, 64, 65));
        jScrollPaneV.setViewportView(panelInsumosVencidos);

        add(jScrollPaneV, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 474, 340, 190));

        fondoPanelInsumosV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/fondoPanelInventarioOtros.png"))); // NOI18N
        add(fondoPanelInsumosV, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 340, 200));

        labelTItuloPR.setBackground(new java.awt.Color(0, 0, 0));
        labelTItuloPR.setFont(new java.awt.Font("Open Sans Medium", 1, 16)); // NOI18N
        labelTItuloPR.setForeground(new java.awt.Color(230, 231, 235));
        labelTItuloPR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTItuloPR.setText("INSUMOS POR REPONER");
        add(labelTItuloPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 340, 50));

        fondoTituloPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/fondoTitulo2.png"))); // NOI18N
        add(fondoTituloPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        jScrollPanePR.setBorder(null);
        jScrollPanePR.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPanePR.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPanePR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPanePR.setViewportView(panelInsumosDisponibles);

        panelInsumosPorReponer.setBackground(new java.awt.Color(58, 64, 65));
        jScrollPanePR.setViewportView(panelInsumosPorReponer);

        add(jScrollPanePR, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 188, 340, 190));

        fondoPanelInsumosPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/fondoPanelInventarioOtros.png"))); // NOI18N
        add(fondoPanelInsumosPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 340, 200));

        labelTItuloD.setBackground(new java.awt.Color(0, 0, 0));
        labelTItuloD.setFont(new java.awt.Font("Open Sans Medium", 1, 16)); // NOI18N
        labelTItuloD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTItuloD.setText("INSUMOS DISPONIBLES");
        add(labelTItuloD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 340, 50));

        fondoTituloD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/fondoTitulo.png"))); // NOI18N
        add(fondoTituloD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jScrollPaneD.setBorder(null);
        jScrollPaneD.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneD.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPaneD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPaneD.setViewportView(panelInsumosDisponibles);

        panelInsumosDisponibles.setBackground(new java.awt.Color(58, 64, 65));
        jScrollPaneD.setViewportView(panelInsumosDisponibles);

        add(jScrollPaneD, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 190, 340, 470));

        fondoPanelInsumosD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/fondoPanelInventarioDisponible.png"))); // NOI18N
        add(fondoPanelInsumosD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 340, 490));

        botonAdvertencia.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonAdvertencia.setForeground(new java.awt.Color(230, 231, 235));
        botonAdvertencia.setBorder(null);
        botonAdvertencia.setBorderPainted(false);
        botonAdvertencia.setContentAreaFilled(false);
        botonAdvertencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAdvertencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAdvertencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAdvertenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAdvertenciaMouseExited(evt);
            }
        });
        add(botonAdvertencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 70, 60));

        fondoBotonAdvertencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoBotonAdvertencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonAdvertencia.png"))); // NOI18N
        add(fondoBotonAdvertencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 70, 60));

        botonProveedor.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonProveedor.setForeground(new java.awt.Color(230, 231, 235));
        botonProveedor.setBorder(null);
        botonProveedor.setBorderPainted(false);
        botonProveedor.setContentAreaFilled(false);
        botonProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonProveedorMouseExited(evt);
            }
        });
        add(botonProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 70, 60));

        fondoBotonProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoBotonProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonProveedor.png"))); // NOI18N
        add(fondoBotonProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 70, 60));

        botonBuscar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(230, 231, 235));
        botonBuscar.setBorder(null);
        botonBuscar.setBorderPainted(false);
        botonBuscar.setContentAreaFilled(false);
        botonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonBuscarMouseExited(evt);
            }
        });
        add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 370, 70, 60));

        fondoBotonBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoBotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonBuscar.png"))); // NOI18N
        add(fondoBotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 370, 70, 60));

        botonSalida.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonSalida.setForeground(new java.awt.Color(230, 231, 235));
        botonSalida.setBorder(null);
        botonSalida.setBorderPainted(false);
        botonSalida.setContentAreaFilled(false);
        botonSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSalidaMouseExited(evt);
            }
        });
        add(botonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, 70, 60));

        fondoBotonSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoBotonSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonSalidas.png"))); // NOI18N
        add(fondoBotonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, 70, 60));

        botonEntrada.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonEntrada.setForeground(new java.awt.Color(230, 231, 235));
        botonEntrada.setBorder(null);
        botonEntrada.setBorderPainted(false);
        botonEntrada.setContentAreaFilled(false);
        botonEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEntradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEntradaMouseExited(evt);
            }
        });
        add(botonEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, 70, 60));

        fondoBotonEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoBotonEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonEntradas.png"))); // NOI18N
        add(fondoBotonEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, 70, 60));

        botonIngresar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(230, 231, 235));
        botonIngresar.setBorder(null);
        botonIngresar.setBorderPainted(false);
        botonIngresar.setContentAreaFilled(false);
        botonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonIngresarMouseExited(evt);
            }
        });
        add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 610, 70, 60));

        fondoBotonIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonIngresar.png"))); // NOI18N
        add(fondoBotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 610, 70, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresarMouseEntered
        // TODO add your handling code here:
        fondoBotonIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonIngresarPresionado.png"))); // NOI18N
    }//GEN-LAST:event_botonIngresarMouseEntered

    private void botonIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresarMouseExited
        // TODO add your handling code here:
        fondoBotonIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonIngresar.png"))); // NOI18N
    }//GEN-LAST:event_botonIngresarMouseExited

    private void botonAdvertenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAdvertenciaMouseEntered
        // TODO add your handling code here:
        if(botonAdvertencia.isEnabled()){
            fondoBotonAdvertencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonAdvertenciaActivadoPresionado.png"))); // NOI18N
        }
    }//GEN-LAST:event_botonAdvertenciaMouseEntered

    private void botonAdvertenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAdvertenciaMouseExited
        // TODO add your handling code here:
        if(botonAdvertencia.isEnabled()){
            fondoBotonAdvertencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonAdvertenciaActivado.png"))); // NOI18N
        }
    }//GEN-LAST:event_botonAdvertenciaMouseExited

    private void botonEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEntradaMouseEntered
        // TODO add your handling code here:
        fondoBotonEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonEntradasPresionado.png")));
    }//GEN-LAST:event_botonEntradaMouseEntered

    private void botonEntradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEntradaMouseExited
        // TODO add your handling code here:
        fondoBotonEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonEntradas.png")));
    }//GEN-LAST:event_botonEntradaMouseExited

    private void botonSalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalidaMouseEntered
        // TODO add your handling code here:
        fondoBotonSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonSalidasPresionado.png")));
    }//GEN-LAST:event_botonSalidaMouseEntered

    private void botonSalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalidaMouseExited
        // TODO add your handling code here:
        fondoBotonSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonSalidas.png")));
    }//GEN-LAST:event_botonSalidaMouseExited

    private void botonBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseEntered
        // TODO add your handling code here:
        fondoBotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonBuscarPresionado.png")));
    }//GEN-LAST:event_botonBuscarMouseEntered

    private void botonBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseExited
        // TODO add your handling code here:
        fondoBotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonBuscar.png")));
    }//GEN-LAST:event_botonBuscarMouseExited

    private void botonProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProveedorMouseEntered
        // TODO add your handling code here:
        fondoBotonProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonProveedorPresionado.png")));
    }//GEN-LAST:event_botonProveedorMouseEntered

    private void botonProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProveedorMouseExited
        // TODO add your handling code here:
        fondoBotonProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewinventario/botonProveedor.png")));
    }//GEN-LAST:event_botonProveedorMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonAdvertencia;
    public javax.swing.JButton botonBuscar;
    public javax.swing.JButton botonEntrada;
    public javax.swing.JButton botonIngresar;
    public javax.swing.JButton botonProveedor;
    public javax.swing.JButton botonSalida;
    public javax.swing.JComboBox<String> comboBoxTipoInsumo;
    public javax.swing.JLabel fondoBotonAdvertencia;
    private javax.swing.JLabel fondoBotonBuscar;
    private javax.swing.JLabel fondoBotonEntrada;
    private javax.swing.JLabel fondoBotonIngresar;
    private javax.swing.JLabel fondoBotonProveedor;
    private javax.swing.JLabel fondoBotonSalida;
    private javax.swing.JLabel fondoComboInsumo;
    private javax.swing.JLabel fondoPanelInsumosD;
    private javax.swing.JLabel fondoPanelInsumosPR;
    private javax.swing.JLabel fondoPanelInsumosV;
    private javax.swing.JLabel fondoTituloD;
    private javax.swing.JLabel fondoTituloPR;
    private javax.swing.JLabel fondoTituloV;
    public javax.swing.JScrollPane jScrollPaneD;
    public javax.swing.JScrollPane jScrollPanePR;
    public javax.swing.JScrollPane jScrollPaneV;
    private javax.swing.JLabel labelTItulo;
    public javax.swing.JLabel labelTItuloD;
    public javax.swing.JLabel labelTItuloPR;
    public javax.swing.JLabel labelTItuloV;
    public javax.swing.JPanel panelInsumosDisponibles;
    public javax.swing.JPanel panelInsumosPorReponer;
    public javax.swing.JPanel panelInsumosVencidos;
    // End of variables declaration//GEN-END:variables
}
