/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewmenu;

/**
 *
 * @author emmez
 */
public class PanelTiempo2 extends javax.swing.JPanel {

    /**
     * Creates new form PanelTiempo2
     */
    public PanelTiempo2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelP2 = new javax.swing.JLabel();
        labelP1 = new javax.swing.JLabel();
        labelTiempo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelFondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelP2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        labelP2.setForeground(new java.awt.Color(230, 231, 235));
        labelP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelP2.setText("Plato");
        add(labelP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 108, 290, -1));

        labelP1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        labelP1.setForeground(new java.awt.Color(230, 231, 235));
        labelP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelP1.setText("Plato");
        add(labelP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 290, -1));

        labelTiempo.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        labelTiempo.setForeground(new java.awt.Color(230, 231, 235));
        labelTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTiempo.setText("Primer tiempo");
        add(labelTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 340, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 197, 41));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 63, 290, 10));

        labelFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/fondoNombreP2.png"))); // NOI18N
        add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 10, 400, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelFondo;
    public javax.swing.JLabel labelP1;
    public javax.swing.JLabel labelP2;
    public javax.swing.JLabel labelTiempo;
    // End of variables declaration//GEN-END:variables
}
