/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewmenu;

/**
 *
 * @author emmez
 */
public class PanelPlato extends javax.swing.JPanel {

    /**
     * Creates new form PanelPlato
     */
    public PanelPlato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonPlato = new javax.swing.JButton();
        labelNombrePlato = new javax.swing.JLabel();
        labelIconoPlato = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonPlato.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonPlato.setForeground(new java.awt.Color(230, 231, 235));
        botonPlato.setBorder(null);
        botonPlato.setBorderPainted(false);
        botonPlato.setContentAreaFilled(false);
        botonPlato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPlato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonPlato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonPlatoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonPlatoMouseExited(evt);
            }
        });
        add(botonPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 10, 262, 50));

        labelNombrePlato.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        labelNombrePlato.setForeground(new java.awt.Color(230, 231, 235));
        labelNombrePlato.setText("Nombre plato");
        add(labelNombrePlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 20, 190, 30));

        labelIconoPlato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/iconoPlato.png"))); // NOI18N
        add(labelIconoPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/fondoNombre.png"))); // NOI18N
        add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonPlatoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPlatoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPlatoMouseEntered

    private void botonPlatoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPlatoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPlatoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonPlato;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelIconoPlato;
    private javax.swing.JLabel labelNombrePlato;
    // End of variables declaration//GEN-END:variables
}
