/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewmenu;

import java.awt.Color;

/**
 *
 * @author emmez
 */
public class PanelIngresarMenuS1 extends javax.swing.JPanel {

    /**
     * Creates new form PanelIngresarMenuS1
     */
    public PanelIngresarMenuS1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonContinuar = new javax.swing.JButton();
        fondoBotonContinuar = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        labelInputP1 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelImagen = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelFondoTItulo = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(39, 45, 47));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonContinuar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonContinuar.setForeground(new java.awt.Color(230, 231, 235));
        botonContinuar.setBorder(null);
        botonContinuar.setBorderPainted(false);
        botonContinuar.setContentAreaFilled(false);
        botonContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonContinuar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonContinuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonContinuarMouseExited(evt);
            }
        });
        add(botonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 50, 50));

        fondoBotonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/botonDerecha.png"))); // NOI18N
        add(fondoBotonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, -1, 50));

        txtNombre.setBackground(new java.awt.Color(0,0,0,1));
        txtNombre.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txtNombre.setForeground(java.awt.Color.lightGray);
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setText("Nombre");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 250, 40));

        labelInputP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/inputMenu.png"))); // NOI18N
        add(labelInputP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        labelTitulo.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        labelTitulo.setText("DATOS DEL MENÚ");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 16, 260, 40));

        labelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/imagenIngresarMenu.png"))); // NOI18N
        add(labelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 20, -1, -1));

        labelNombre.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(230, 231, 235));
        labelNombre.setText("Nombre del Menú");
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 290, -1));

        labelFondoTItulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/fondoTituloDatosMenu.png"))); // NOI18N
        add(labelFondoTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/fondoIngresarMenu.png"))); // NOI18N
        add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 385, 615));
    }// </editor-fold>//GEN-END:initComponents

    private void botonContinuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonContinuarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonContinuarMouseEntered

    private void botonContinuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonContinuarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonContinuarMouseExited

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        // TODO add your handling code here:
        if(txtNombre.getText().equals("Nombre")){
            txtNombre.setText("");
            txtNombre.setForeground(new Color(230,231,235));
        }
    }//GEN-LAST:event_txtNombreMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonContinuar;
    public javax.swing.JLabel fondoBotonContinuar;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelFondoTItulo;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelInputP1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTitulo;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
