/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewmenu;

/**
 *
 * @author emmez
 */
public class PanelBebida extends javax.swing.JPanel {

    /**
     * Creates new form PanelBebida
     */
    public PanelBebida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonBebida = new javax.swing.JButton();
        labelNombreBebida = new javax.swing.JLabel();
        labelIconoBebida = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonBebida.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonBebida.setForeground(new java.awt.Color(230, 231, 235));
        botonBebida.setBorder(null);
        botonBebida.setBorderPainted(false);
        botonBebida.setContentAreaFilled(false);
        botonBebida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBebida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonBebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonBebidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonBebidaMouseExited(evt);
            }
        });
        add(botonBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 10, 262, 50));

        labelNombreBebida.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        labelNombreBebida.setForeground(new java.awt.Color(230, 231, 235));
        labelNombreBebida.setText("Nombre bebida");
        add(labelNombreBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 20, 190, 30));

        labelIconoBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/iconoBebida.png"))); // NOI18N
        add(labelIconoBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 20, -1, 30));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/fondoNombre.png"))); // NOI18N
        add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonBebidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBebidaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBebidaMouseEntered

    private void botonBebidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBebidaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBebidaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonBebida;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelIconoBebida;
    public javax.swing.JLabel labelNombreBebida;
    // End of variables declaration//GEN-END:variables
}
