/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewmenu;

/**
 *
 * @author emmez
 */
public class PanelMenu extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenu
     */
    public PanelMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonMenu = new javax.swing.JButton();
        labelNombreMenu = new javax.swing.JLabel();
        labelIconoMenu = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonMenu.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonMenu.setForeground(new java.awt.Color(230, 231, 235));
        botonMenu.setBorder(null);
        botonMenu.setBorderPainted(false);
        botonMenu.setContentAreaFilled(false);
        botonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMenuMouseExited(evt);
            }
        });
        add(botonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 10, 262, 50));

        labelNombreMenu.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        labelNombreMenu.setForeground(new java.awt.Color(230, 231, 235));
        labelNombreMenu.setText("Nombre menu");
        add(labelNombreMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 20, 190, 30));

        labelIconoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/iconMenu.png"))); // NOI18N
        add(labelIconoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 20, -1, 30));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/fondoNombre.png"))); // NOI18N
        add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMenuMouseEntered

    private void botonMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMenuMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonMenu;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelIconoMenu;
    private javax.swing.JLabel labelNombreMenu;
    // End of variables declaration//GEN-END:variables
}
