/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewmenu;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import model.modelview.MyComboBoxRender;

/**
 *
 * @author emmez
 */
public class PanelIngresarPlato extends javax.swing.JPanel {

    /**
     * Creates new form PanelIngresarPlato
     */
    public PanelIngresarPlato() {
        initComponents();
        comboBoxCategoria .setOpaque(false);
        comboBoxCategoria.setEditable(true);
        JTextField boxField = (JTextField)comboBoxCategoria .getEditor().getEditorComponent();
        boxField.setBorder(BorderFactory.createEmptyBorder());
        boxField.setForeground(Color.LIGHT_GRAY);
        boxField.setBackground(new Color(0, 0, 0, 0));
        boxField.setFocusable(false);
        comboBoxCategoria.setRenderer(new MyComboBoxRender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegresar = new javax.swing.JButton();
        fondoBotonRegresar = new javax.swing.JLabel();
        labelInputP2 = new javax.swing.JLabel();
        comboBoxCategoria = new javax.swing.JComboBox<>();
        labelInputP1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        labelInputP = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JButton();
        fondoBotonRegistrar = new javax.swing.JLabel();
        labelImagen = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelFondoTitulo = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(39, 45, 47));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRegresar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonRegresar.setForeground(new java.awt.Color(230, 231, 235));
        botonRegresar.setBorder(null);
        botonRegresar.setBorderPainted(false);
        botonRegresar.setContentAreaFilled(false);
        botonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresarMouseExited(evt);
            }
        });
        add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 50, 50));

        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/botonRegresar.png"))); // NOI18N
        add(fondoBotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 50));

        labelInputP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInputP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/inputGrande.png"))); // NOI18N
        add(labelInputP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 380, -1));

        comboBoxCategoria.setBackground(new java.awt.Color(86, 92, 94));
        comboBoxCategoria.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        comboBoxCategoria.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoría" }));
        comboBoxCategoria.setBorder(null);
        comboBoxCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 270, 40));

        labelInputP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInputP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/inpuPeque.png"))); // NOI18N
        add(labelInputP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 380, -1));

        txtNombre.setBackground(new java.awt.Color(0,0,0,1));
        txtNombre.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txtNombre.setForeground(java.awt.Color.lightGray);
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setText("Nombre");
        txtNombre.setBorder(null);
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 270, 40));

        labelInputP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInputP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/inpuPeque.png"))); // NOI18N
        add(labelInputP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 380, -1));

        botonRegistrar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(39, 45, 47));
        botonRegistrar.setText("Registrar");
        botonRegistrar.setBorder(null);
        botonRegistrar.setBorderPainted(false);
        botonRegistrar.setContentAreaFilled(false);
        botonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseExited(evt);
            }
        });
        add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 150, 50));

        fondoBotonRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoBotonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/botonRegistrarPoB.png"))); // NOI18N
        add(fondoBotonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 530, 300, 50));

        labelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/imagenIngresarPlato.png"))); // NOI18N
        add(labelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        labelTitulo.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        labelTitulo.setText("DATOS DEL PLATO");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 116, -1, 40));

        labelFondoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/fondoTItuloIngresarPoB.png"))); // NOI18N
        add(labelFondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewmenu/fondoIngresarPoB.png"))); // NOI18N
        add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        txtDescripcion.setBackground(new java.awt.Color(67, 73, 75));
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(230, 231, 235));
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 300, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarMouseEntered

    private void botonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarMouseExited

    private void botonRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistrarMouseEntered

    private void botonRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistrarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonRegistrar;
    public javax.swing.JButton botonRegresar;
    public javax.swing.JComboBox<String> comboBoxCategoria;
    public javax.swing.JLabel fondoBotonRegistrar;
    public javax.swing.JLabel fondoBotonRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelFondoTitulo;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelInputP;
    private javax.swing.JLabel labelInputP1;
    private javax.swing.JLabel labelInputP2;
    private javax.swing.JLabel labelTitulo;
    public javax.swing.JTextArea txtDescripcion;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
