/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.viewusuarios;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author emmez
 */
public class FrameReestablecer extends javax.swing.JFrame {

    /**
     * Creates new form FrameAsignarRol
     */
    public FrameReestablecer() {
        initComponents();
        setIconImage(getIconImage());
    }
    
    @Override
    public Image getIconImage () {  
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/imagesviewprincipal/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCambiar = new javax.swing.JButton();
        fondoBotonGuardar = new javax.swing.JLabel();
        txtPassConfirmada = new javax.swing.JPasswordField();
        txtPassNueva = new javax.swing.JPasswordField();
        txtPassActual = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelTItulo = new javax.swing.JLabel();
        labelFondoTitulo = new javax.swing.JLabel();
        labelFondo2 = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(39, 45, 47));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCambiar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonCambiar.setForeground(new java.awt.Color(39, 45, 47));
        botonCambiar.setText("Cambiar");
        botonCambiar.setBorder(null);
        botonCambiar.setBorderPainted(false);
        botonCambiar.setContentAreaFilled(false);
        botonCambiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCambiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCambiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCambiarMouseExited(evt);
            }
        });
        botonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 140, 50));

        fondoBotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoBotonGuardarA.png"))); // NOI18N
        getContentPane().add(fondoBotonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 150, 50));

        txtPassConfirmada.setFont(new java.awt.Font("Open Sans Medium", 0, 15)); // NOI18N
        getContentPane().add(txtPassConfirmada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 280, 40));

        txtPassNueva.setFont(new java.awt.Font("Open Sans Medium", 0, 15)); // NOI18N
        getContentPane().add(txtPassNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 280, 40));

        txtPassActual.setFont(new java.awt.Font("Open Sans Medium", 0, 15)); // NOI18N
        getContentPane().add(txtPassActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 280, 40));

        jLabel3.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 231, 235));
        jLabel3.setText("Confirmar contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 270, -1));

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 231, 235));
        jLabel2.setText("Nueva contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 270, -1));

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 231, 235));
        jLabel1.setText("Contraseña actual");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 270, -1));

        labelTItulo.setBackground(new java.awt.Color(0, 0, 0));
        labelTItulo.setFont(new java.awt.Font("Open Sans Medium", 1, 16)); // NOI18N
        labelTItulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTItulo.setText("REESTABLECER CONTRASEÑA");
        getContentPane().add(labelTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 50));

        labelFondoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoTituloAsignar.png"))); // NOI18N
        getContentPane().add(labelFondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labelFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoPanelAsignar.png"))); // NOI18N
        getContentPane().add(labelFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 440));

        labelFondo.setBackground(new java.awt.Color(39, 45, 47));
        labelFondo.setOpaque(true);
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCambiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCambiarMouseEntered
        // TODO add your handling code here:
        fondoBotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoBotonGuardarAPresionado.png")));
    }//GEN-LAST:event_botonCambiarMouseEntered

    private void botonCambiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCambiarMouseExited
        // TODO add your handling code here:
        fondoBotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoBotonGuardarA.png")));
    }//GEN-LAST:event_botonCambiarMouseExited

    private void botonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameReestablecer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameReestablecer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameReestablecer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameReestablecer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameReestablecer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonCambiar;
    public javax.swing.JLabel fondoBotonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelFondo2;
    private javax.swing.JLabel labelFondoTitulo;
    public javax.swing.JLabel labelTItulo;
    public javax.swing.JPasswordField txtPassActual;
    public javax.swing.JPasswordField txtPassConfirmada;
    public javax.swing.JPasswordField txtPassNueva;
    // End of variables declaration//GEN-END:variables
}
