/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.viewusuarios;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author emmez
 */
public class FrameAsignarRol extends javax.swing.JFrame {

    /**
     * Creates new form FrameAsignarRol
     */
    public FrameAsignarRol() {
        initComponents();
        setIconImage(getIconImage());
        labelMenus.setVisible(false);
        botonMenu.setVisible(false);
    }
    
    @Override
    public Image getIconImage () {  
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/imagesviewprincipal/logo.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonGuardar = new javax.swing.JButton();
        fondoBotonGuardar = new javax.swing.JLabel();
        labelMenus = new javax.swing.JLabel();
        labelInventario = new javax.swing.JLabel();
        labelEmpleados = new javax.swing.JLabel();
        labelReservaciones = new javax.swing.JLabel();
        labelSubtitulo2 = new javax.swing.JLabel();
        labelSubtitulo = new javax.swing.JLabel();
        botonMenu = new javax.swing.JRadioButton();
        botonInventario = new javax.swing.JRadioButton();
        botonEmpleados = new javax.swing.JRadioButton();
        botonReservaciones = new javax.swing.JRadioButton();
        labelTItulo = new javax.swing.JLabel();
        labelFondoTitulo = new javax.swing.JLabel();
        labelFondo2 = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(39, 45, 47));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonGuardar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(39, 45, 47));
        botonGuardar.setText("Guardar");
        botonGuardar.setBorder(null);
        botonGuardar.setBorderPainted(false);
        botonGuardar.setContentAreaFilled(false);
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGuardarMouseExited(evt);
            }
        });
        getContentPane().add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 140, 50));

        fondoBotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoBotonGuardarA.png"))); // NOI18N
        getContentPane().add(fondoBotonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, 50));

        labelMenus.setBackground(new java.awt.Color(230, 231, 235));
        labelMenus.setFont(new java.awt.Font("Open Sans SemiBold", 0, 16)); // NOI18N
        labelMenus.setForeground(new java.awt.Color(230, 231, 235));
        labelMenus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMenus.setText("Menús");
        getContentPane().add(labelMenus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 120, 20));

        labelInventario.setBackground(new java.awt.Color(230, 231, 235));
        labelInventario.setFont(new java.awt.Font("Open Sans SemiBold", 0, 16)); // NOI18N
        labelInventario.setForeground(new java.awt.Color(230, 231, 235));
        labelInventario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelInventario.setText("Inventario");
        getContentPane().add(labelInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 120, 20));

        labelEmpleados.setBackground(new java.awt.Color(230, 231, 235));
        labelEmpleados.setFont(new java.awt.Font("Open Sans SemiBold", 0, 16)); // NOI18N
        labelEmpleados.setForeground(new java.awt.Color(230, 231, 235));
        labelEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEmpleados.setText("Empleados");
        getContentPane().add(labelEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 120, 20));

        labelReservaciones.setBackground(new java.awt.Color(230, 231, 235));
        labelReservaciones.setFont(new java.awt.Font("Open Sans SemiBold", 0, 16)); // NOI18N
        labelReservaciones.setForeground(new java.awt.Color(230, 231, 235));
        labelReservaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelReservaciones.setText("Reservaciones");
        getContentPane().add(labelReservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, 20));

        labelSubtitulo2.setBackground(new java.awt.Color(230, 231, 235));
        labelSubtitulo2.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        labelSubtitulo2.setForeground(new java.awt.Color(230, 231, 235));
        labelSubtitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtitulo2.setText("(Visibilidad)");
        getContentPane().add(labelSubtitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 290, 20));

        labelSubtitulo.setBackground(new java.awt.Color(230, 231, 235));
        labelSubtitulo.setFont(new java.awt.Font("Open Sans SemiBold", 1, 17)); // NOI18N
        labelSubtitulo.setForeground(new java.awt.Color(230, 231, 235));
        labelSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtitulo.setText("Gestiones del Restaurante");
        getContentPane().add(labelSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 290, 20));
        getContentPane().add(botonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));
        getContentPane().add(botonInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));
        getContentPane().add(botonEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));
        getContentPane().add(botonReservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        labelTItulo.setBackground(new java.awt.Color(0, 0, 0));
        labelTItulo.setFont(new java.awt.Font("Open Sans Medium", 1, 16)); // NOI18N
        labelTItulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTItulo.setText("ASIGNAR ROL");
        getContentPane().add(labelTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 50));

        labelFondoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoTituloAsignar.png"))); // NOI18N
        getContentPane().add(labelFondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labelFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoPanelAsignar.png"))); // NOI18N
        getContentPane().add(labelFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 440));

        labelFondo.setBackground(new java.awt.Color(39, 45, 47));
        labelFondo.setOpaque(true);
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseEntered
        // TODO add your handling code here:
        fondoBotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoBotonGuardarAPresionado.png")));
    }//GEN-LAST:event_botonGuardarMouseEntered

    private void botonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseExited
        // TODO add your handling code here:
        fondoBotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoBotonGuardarA.png")));
    }//GEN-LAST:event_botonGuardarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAsignarRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAsignarRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAsignarRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAsignarRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAsignarRol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton botonEmpleados;
    public javax.swing.JButton botonGuardar;
    public javax.swing.JRadioButton botonInventario;
    public javax.swing.JRadioButton botonMenu;
    public javax.swing.JRadioButton botonReservaciones;
    public javax.swing.JLabel fondoBotonGuardar;
    private javax.swing.JLabel labelEmpleados;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelFondo2;
    private javax.swing.JLabel labelFondoTitulo;
    private javax.swing.JLabel labelInventario;
    private javax.swing.JLabel labelMenus;
    private javax.swing.JLabel labelReservaciones;
    private javax.swing.JLabel labelSubtitulo;
    private javax.swing.JLabel labelSubtitulo2;
    public javax.swing.JLabel labelTItulo;
    // End of variables declaration//GEN-END:variables
}
