/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewusuarios;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import model.modelview.MyComboBoxRender;
import java.awt.GridLayout;

/**
 *
 * @author Estefany Torres
 */
public class PanelConsultarUsuarios extends javax.swing.JPanel {

    public PanelConsultarUsuarios() {
        initComponents();
        
        comboBoxUsuario.setOpaque(false);
        comboBoxUsuario.setEditable(true);
        JTextField boxField = (JTextField)comboBoxUsuario .getEditor().getEditorComponent();
        boxField.setBorder(BorderFactory.createEmptyBorder());
        boxField.setForeground(new Color(39,45,47));
        boxField.setBackground(new Color(0, 0, 0, 0));
        boxField.setFocusable(false);
        comboBoxUsuario.setRenderer(new MyComboBoxRender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegresar = new javax.swing.JButton();
        fondoBotonRegresar = new javax.swing.JLabel();
        comboBoxUsuario = new javax.swing.JComboBox<>();
        fondoComboUsuario = new javax.swing.JLabel();
        labelTItulo = new javax.swing.JLabel();
        fondoTitulo = new javax.swing.JLabel();
        labelCirculo = new javax.swing.JLabel();
        labelFotoPerfil = new javax.swing.JLabel();
        labelLinea = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        labelCedula = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelRoles = new javax.swing.JLabel();
        labelResponsable = new javax.swing.JLabel();
        iconoRoles = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        iconoTelefono = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        iconoEdad = new javax.swing.JLabel();
        labelSexo = new javax.swing.JLabel();
        iconoSexo = new javax.swing.JLabel();
        labelMunicipio = new javax.swing.JLabel();
        iconoMunicipio = new javax.swing.JLabel();
        labelMail = new javax.swing.JLabel();
        iconoMail = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        iconoUser = new javax.swing.JLabel();
        fondoDetalleUsuarioA = new javax.swing.JLabel();
        fondoDetalleUsuarioP = new javax.swing.JLabel();
        botonEliminar = new javax.swing.JButton();
        fondoBotonEliminar = new javax.swing.JLabel();
        botonAsignar = new javax.swing.JButton();
        iconoAsignar = new javax.swing.JLabel();
        fondoBotonAsignar = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        iconoAceptar = new javax.swing.JLabel();
        fondoBotonAceptar = new javax.swing.JLabel();
        botonRechazar = new javax.swing.JButton();
        iconoRechazar = new javax.swing.JLabel();
        fondoBotonRechazar = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        panelUsuarios = new javax.swing.JPanel(new GridLayout(0, 1, 1, 1));
        fondoPanelUsuarios = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        labelBuscar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(39, 45, 47));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRegresar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonRegresar.setForeground(new java.awt.Color(230, 231, 235));
        botonRegresar.setBorder(null);
        botonRegresar.setBorderPainted(false);
        botonRegresar.setContentAreaFilled(false);
        botonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresarMouseExited(evt);
            }
        });
        add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 50, 50));

        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoRegresar.png"))); // NOI18N
        add(fondoBotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 50));

        comboBoxUsuario.setBackground(new java.awt.Color(86, 92, 94));
        comboBoxUsuario.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        comboBoxUsuario.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuarios Activos", "Usuarios Pendientes" }));
        comboBoxUsuario.setBorder(null);
        comboBoxUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comboBoxUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 68, 260, 35));

        fondoComboUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoComboUsuario.png"))); // NOI18N
        add(fondoComboUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 310, 50));

        labelTItulo.setBackground(new java.awt.Color(0, 0, 0));
        labelTItulo.setFont(new java.awt.Font("Open Sans Medium", 1, 16)); // NOI18N
        labelTItulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTItulo.setText("USUARIOS");
        add(labelTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 310, 50));

        fondoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoTItulo.png"))); // NOI18N
        add(fondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        labelCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/circuloVerde.png"))); // NOI18N
        add(labelCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 90, 130, 130));
        add(labelFotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 90, 130, 130));

        labelLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/lineaVerde.png"))); // NOI18N
        add(labelLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, 20));

        labelStatus.setFont(new java.awt.Font("Open Sans", 2, 14)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(152, 255, 163));
        labelStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelStatus.setText("Usuario Activo");
        add(labelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 220, -1));

        labelCedula.setFont(new java.awt.Font("Open Sans SemiBold", 0, 16)); // NOI18N
        labelCedula.setForeground(new java.awt.Color(230, 231, 235));
        labelCedula.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCedula.setText("CI: 12456789");
        add(labelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 220, -1));

        labelNombre.setFont(new java.awt.Font("Open Sans SemiBold", 0, 22)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(230, 231, 235));
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNombre.setText("Nombre Apellido");
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 220, -1));

        labelRoles.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        labelRoles.setForeground(new java.awt.Color(230, 231, 235));
        labelRoles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRoles.setText("Inventario");
        add(labelRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 300, -1));

        labelResponsable.setFont(new java.awt.Font("Open Sans SemiBold", 1, 15)); // NOI18N
        labelResponsable.setForeground(new java.awt.Color(230, 231, 235));
        labelResponsable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelResponsable.setText("Responsable de:");
        add(labelResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 240, 20));

        iconoRoles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/iconoRoles.png"))); // NOI18N
        add(iconoRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 530, 40, 70));

        labelTelefono.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        labelTelefono.setForeground(new java.awt.Color(230, 231, 235));
        labelTelefono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTelefono.setText("Número");
        add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 240, 30));

        iconoTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/iconoTelefono.png"))); // NOI18N
        add(iconoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, -1, 30));

        labelEdad.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        labelEdad.setForeground(new java.awt.Color(230, 231, 235));
        labelEdad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEdad.setText("Edad");
        add(labelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 240, 30));

        iconoEdad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/iconoEdad.png"))); // NOI18N
        add(iconoEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, 30));

        labelSexo.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        labelSexo.setForeground(new java.awt.Color(230, 231, 235));
        labelSexo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSexo.setText("Sexo");
        add(labelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 240, 30));

        iconoSexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/iconoSexo.png"))); // NOI18N
        add(iconoSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, 30));

        labelMunicipio.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        labelMunicipio.setForeground(new java.awt.Color(230, 231, 235));
        labelMunicipio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMunicipio.setText("Municipio");
        add(labelMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 240, 30));

        iconoMunicipio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/iconoLocation.png"))); // NOI18N
        add(iconoMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, 30));

        labelMail.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        labelMail.setForeground(new java.awt.Color(230, 231, 235));
        labelMail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMail.setText("Correo");
        add(labelMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 240, 30));

        iconoMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/iconoMail.png"))); // NOI18N
        add(iconoMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        labelUser.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        labelUser.setForeground(new java.awt.Color(230, 231, 235));
        labelUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelUser.setText("Username");
        add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 240, 20));

        iconoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/iconoUser.png"))); // NOI18N
        add(iconoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        fondoDetalleUsuarioA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoPanelDetalleUsuarioA.png"))); // NOI18N
        add(fondoDetalleUsuarioA, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 410, 550));

        fondoDetalleUsuarioP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoPanelDetalleUsuario.png"))); // NOI18N
        add(fondoDetalleUsuarioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 410, 300));

        botonEliminar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(39, 45, 47));
        botonEliminar.setBorder(null);
        botonEliminar.setBorderPainted(false);
        botonEliminar.setContentAreaFilled(false);
        botonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEliminarMouseExited(evt);
            }
        });
        add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 620, 40, 40));

        fondoBotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/BotonEliminar.png"))); // NOI18N
        add(fondoBotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 610, -1, 60));

        botonAsignar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonAsignar.setForeground(new java.awt.Color(39, 45, 47));
        botonAsignar.setText("        Asignar Rol");
        botonAsignar.setBorder(null);
        botonAsignar.setBorderPainted(false);
        botonAsignar.setContentAreaFilled(false);
        botonAsignar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAsignar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAsignar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAsignarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAsignarMouseExited(evt);
            }
        });
        add(botonAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 620, 160, 40));

        iconoAsignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/iconRol.png"))); // NOI18N
        add(iconoAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 620, -1, 40));

        fondoBotonAsignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoBotonAsignar.png"))); // NOI18N
        add(fondoBotonAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 610, -1, 60));

        botonAceptar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonAceptar.setForeground(new java.awt.Color(39, 45, 47));
        botonAceptar.setText("      ACEPTAR");
        botonAceptar.setBorder(null);
        botonAceptar.setBorderPainted(false);
        botonAceptar.setContentAreaFilled(false);
        botonAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAceptarMouseExited(evt);
            }
        });
        add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 620, 160, 40));

        iconoAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/iconoAceptar.png"))); // NOI18N
        add(iconoAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 620, -1, 40));

        fondoBotonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoBotonAceptar.png"))); // NOI18N
        add(fondoBotonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 610, -1, 60));

        botonRechazar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonRechazar.setForeground(new java.awt.Color(39, 45, 47));
        botonRechazar.setText("      RECHAZAR");
        botonRechazar.setBorder(null);
        botonRechazar.setBorderPainted(false);
        botonRechazar.setContentAreaFilled(false);
        botonRechazar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRechazar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRechazar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRechazarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRechazarMouseExited(evt);
            }
        });
        add(botonRechazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 160, 40));

        iconoRechazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/iconoRechazar.png"))); // NOI18N
        add(iconoRechazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, -1, 40));

        fondoBotonRechazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoBotonRechazar.png"))); // NOI18N
        add(fondoBotonRechazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 610, 180, 60));

        jScrollPane.setBorder(null);
        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane.setViewportView(panelUsuarios);

        panelUsuarios.setBackground(new java.awt.Color(58, 64, 65));
        jScrollPane.setViewportView(panelUsuarios);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 250, 310, 410));

        fondoPanelUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoPanelUsuarios.png"))); // NOI18N
        add(fondoPanelUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 310, 430));

        txtBuscar.setBackground(new java.awt.Color(0,0,0,1));
        txtBuscar.setFont(new java.awt.Font("Open Sans Medium", 0, 16)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(230, 231, 235));
        txtBuscar.setBorder(null);
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 240, 42));

        labelBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/barraBuscar.png"))); // NOI18N
        add(labelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 116, 310, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void botonRechazarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRechazarMouseEntered
        // TODO add your handling code here:
        fondoBotonRechazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoBotonRechazarPresionado.png"))); // NOI18N
    }//GEN-LAST:event_botonRechazarMouseEntered

    private void botonRechazarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRechazarMouseExited
        // TODO add your handling code here:
        fondoBotonRechazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoBotonRechazar.png"))); // NOI18N
    }//GEN-LAST:event_botonRechazarMouseExited

    private void botonAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseEntered
        // TODO add your handling code here:
        fondoBotonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoBotonAceptarPresionado.png"))); // NOI18N
    }//GEN-LAST:event_botonAceptarMouseEntered

    private void botonAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseExited
        // TODO add your handling code here:
        fondoBotonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoBotonAceptar.png"))); // NOI18N
    }//GEN-LAST:event_botonAceptarMouseExited

    private void botonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseEntered
        // TODO add your handling code here:
        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoRegresarPresionado.png"))); // NOI18N
    }//GEN-LAST:event_botonRegresarMouseEntered

    private void botonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseExited
        // TODO add your handling code here:
        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoRegresar.png"))); // NOI18N
    }//GEN-LAST:event_botonRegresarMouseExited

    private void botonAsignarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAsignarMouseEntered
        // TODO add your handling code here:
        fondoBotonAsignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoBotonAsignarPresionado.png")));
    }//GEN-LAST:event_botonAsignarMouseEntered

    private void botonAsignarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAsignarMouseExited
        // TODO add your handling code here:
        fondoBotonAsignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoBotonAsignar.png")));
    }//GEN-LAST:event_botonAsignarMouseExited

    private void botonEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseEntered
        // TODO add your handling code here:
        fondoBotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/BotonEliminar.png")));
    }//GEN-LAST:event_botonEliminarMouseEntered

    private void botonEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseExited
        // TODO add your handling code here:
        fondoBotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/BotonEliminarPresionado.png")));
    }//GEN-LAST:event_botonEliminarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonAceptar;
    public javax.swing.JButton botonAsignar;
    public javax.swing.JButton botonEliminar;
    public javax.swing.JButton botonRechazar;
    public javax.swing.JButton botonRegresar;
    public javax.swing.JComboBox<String> comboBoxUsuario;
    public javax.swing.JLabel fondoBotonAceptar;
    public javax.swing.JLabel fondoBotonAsignar;
    public javax.swing.JLabel fondoBotonEliminar;
    public javax.swing.JLabel fondoBotonRechazar;
    public javax.swing.JLabel fondoBotonRegresar;
    private javax.swing.JLabel fondoComboUsuario;
    public javax.swing.JLabel fondoDetalleUsuarioA;
    public javax.swing.JLabel fondoDetalleUsuarioP;
    private javax.swing.JLabel fondoPanelUsuarios;
    private javax.swing.JLabel fondoTitulo;
    public javax.swing.JLabel iconoAceptar;
    public javax.swing.JLabel iconoAsignar;
    public javax.swing.JLabel iconoEdad;
    public javax.swing.JLabel iconoMail;
    public javax.swing.JLabel iconoMunicipio;
    public javax.swing.JLabel iconoRechazar;
    public javax.swing.JLabel iconoRoles;
    public javax.swing.JLabel iconoSexo;
    public javax.swing.JLabel iconoTelefono;
    public javax.swing.JLabel iconoUser;
    public javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel labelBuscar;
    public javax.swing.JLabel labelCedula;
    public javax.swing.JLabel labelCirculo;
    public javax.swing.JLabel labelEdad;
    public javax.swing.JLabel labelFotoPerfil;
    public javax.swing.JLabel labelLinea;
    public javax.swing.JLabel labelMail;
    public javax.swing.JLabel labelMunicipio;
    public javax.swing.JLabel labelNombre;
    public javax.swing.JLabel labelResponsable;
    public javax.swing.JLabel labelRoles;
    public javax.swing.JLabel labelSexo;
    public javax.swing.JLabel labelStatus;
    public javax.swing.JLabel labelTItulo;
    public javax.swing.JLabel labelTelefono;
    public javax.swing.JLabel labelUser;
    public javax.swing.JPanel panelUsuarios;
    public javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
