/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewusuarios;

/**
 *
 * @author Estefany Torres
 */
public class PanelUsuarioActivo extends javax.swing.JPanel {

    public PanelUsuarioActivo() {
        initComponents();
        fondoUsuarioPresionado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonUsuario = new javax.swing.JButton();
        iconoUsuario = new javax.swing.JLabel();
        fondoUsuarioPresionado = new javax.swing.JLabel();
        fondoUsuario = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonUsuario.setFont(new java.awt.Font("Open Sans SemiBold", 0, 16)); // NOI18N
        botonUsuario.setForeground(new java.awt.Color(230, 231, 235));
        botonUsuario.setText("Usuario");
        botonUsuario.setBorder(null);
        botonUsuario.setBorderPainted(false);
        botonUsuario.setContentAreaFilled(false);
        botonUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonUsuarioMouseExited(evt);
            }
        });
        add(botonUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 9, 230, 60));

        iconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/iconoUsuarioVerde.png"))); // NOI18N
        add(iconoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 19, -1, 40));

        fondoUsuarioPresionado.setBackground(new java.awt.Color(102, 102, 102));
        fondoUsuarioPresionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoUsuarioPresionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoUsuario.png"))); // NOI18N
        add(fondoUsuarioPresionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 9, 280, 60));

        fondoUsuario.setBackground(new java.awt.Color(102, 102, 102));
        fondoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewusuarios/fondoUsuario.png"))); // NOI18N
        add(fondoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 9, 280, 60));
        add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonUsuarioMouseEntered
        // TODO add your handling code here:
        fondoUsuarioPresionado.setVisible(true);
    }//GEN-LAST:event_botonUsuarioMouseEntered

    private void botonUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonUsuarioMouseExited
        // TODO add your handling code here:
        fondoUsuarioPresionado.setVisible(false);
    }//GEN-LAST:event_botonUsuarioMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonUsuario;
    private javax.swing.JLabel fondoUsuario;
    private javax.swing.JLabel fondoUsuarioPresionado;
    private javax.swing.JLabel iconoUsuario;
    public javax.swing.JLabel labelUser;
    // End of variables declaration//GEN-END:variables
}
