/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewlogin;

import java.awt.Color;

/**
 *
 * @author Estefany Torres
 */
public class PanelCrearCuenta extends javax.swing.JPanel {


    public PanelCrearCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        txtCorreo = new javax.swing.JTextField();
        crearCuenta = new javax.swing.JLabel();
        imagenDecorativa = new javax.swing.JLabel();
        inputPass = new javax.swing.JLabel();
        inputCorreo = new javax.swing.JLabel();
        inputApellido = new javax.swing.JLabel();
        inputNombre = new javax.swing.JLabel();
        botonCrearCuenta = new javax.swing.JButton();
        fondoBotonCrear = new javax.swing.JLabel();
        recuadroFondo = new javax.swing.JLabel();
        labelMiembro = new javax.swing.JLabel();
        botonIniciar = new javax.swing.JButton();
        fondoBotonIniciar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(39, 45, 47));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApellido.setBackground(new java.awt.Color(0,0,0,1));
        txtApellido.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(204, 204, 204));
        txtApellido.setText("Apellido");
        txtApellido.setBorder(null);
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoMousePressed(evt);
            }
        });
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 225, 130, 40));

        txtNombre.setBackground(new java.awt.Color(0,0,0,1));
        txtNombre.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("Nombre");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 225, 130, 40));

        txtPass.setBackground(new java.awt.Color(0,0,0,1));
        txtPass.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtPass.setForeground(new java.awt.Color(204, 204, 204));
        txtPass.setText("******");
        txtPass.setBorder(null);
        txtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPassMousePressed(evt);
            }
        });
        add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 310, 50));

        txtCorreo.setBackground(new java.awt.Color(0,0,0,1));
        txtCorreo.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(204, 204, 204));
        txtCorreo.setText("Correo");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 310, 50));

        crearCuenta.setFont(new java.awt.Font("Open Sans", 1, 31)); // NOI18N
        crearCuenta.setForeground(new java.awt.Color(230, 231, 235));
        crearCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearCuenta.setText("Crear cuenta");
        add(crearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 440, -1));

        imagenDecorativa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewlogin/ImagenDecorativaInicio.png"))); // NOI18N
        add(imagenDecorativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1030, -1));

        inputPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewlogin/Barra2InputCrear.png"))); // NOI18N
        add(inputPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 390, 70));

        inputCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewlogin/Barra2InputCrear.png"))); // NOI18N
        add(inputCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 390, 70));

        inputApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewlogin/Barra1InputCrear.png"))); // NOI18N
        add(inputApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 190, 50));

        inputNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewlogin/Barra1InputCrear.png"))); // NOI18N
        add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 190, 50));

        botonCrearCuenta.setFont(new java.awt.Font("Open Sans SemiBold", 0, 19)); // NOI18N
        botonCrearCuenta.setForeground(new java.awt.Color(230, 231, 235));
        botonCrearCuenta.setText("Crear");
        botonCrearCuenta.setBorder(null);
        botonCrearCuenta.setBorderPainted(false);
        botonCrearCuenta.setContentAreaFilled(false);
        botonCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCrearCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCrearCuentaMouseExited(evt);
            }
        });
        add(botonCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 418, 100, 50));

        fondoBotonCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewlogin/BotonNaranjaInicio.png"))); // NOI18N
        add(fondoBotonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, -1));

        recuadroFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recuadroFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewlogin/RecuadroFondoCrearCuenta.png"))); // NOI18N
        add(recuadroFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 460, 340));

        labelMiembro.setBackground(new java.awt.Color(153, 153, 153));
        labelMiembro.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        labelMiembro.setForeground(java.awt.Color.lightGray);
        labelMiembro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelMiembro.setText("¿Ya eres miembro?");
        labelMiembro.setToolTipText("");
        add(labelMiembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 46, 220, 30));

        botonIniciar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 14)); // NOI18N
        botonIniciar.setForeground(new java.awt.Color(230, 231, 235));
        botonIniciar.setText("Iniciar sesión");
        botonIniciar.setBorder(null);
        botonIniciar.setBorderPainted(false);
        botonIniciar.setContentAreaFilled(false);
        botonIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonIniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonIniciarMouseExited(evt);
            }
        });
        add(botonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 140, 40));

        fondoBotonIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewlogin/BotonAmarilloCrearCuenta.png"))); // NOI18N
        add(fondoBotonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 140, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        // TODO add your handling code here:
        if(txtNombre.getText().equals("Nombre")){
            txtNombre.setText("");
            txtNombre.setForeground(new Color(230,231,235));
        }
        
        if(txtApellido.getText().isEmpty()){
            txtApellido.setText("Apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(Color.LIGHT_GRAY);
        }
        if(String.valueOf(txtPass.getPassword()).isEmpty()){
            txtPass.setText("******");
            txtPass.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMousePressed
        // TODO add your handling code here:
        if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
 
        if(txtApellido.getText().equals("Apellido")){
            txtApellido.setText("");
            txtApellido.setForeground(new Color(230,231,235));
        }

        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(Color.LIGHT_GRAY);
        }
        if(String.valueOf(txtPass.getPassword()).isEmpty()){
            txtPass.setText("******");
            txtPass.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtApellidoMousePressed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
        if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtApellido.getText().isEmpty()){
            txtApellido.setText("Apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCorreo.getText().equals("Correo")){
            txtCorreo.setText("");
            txtCorreo.setForeground(new Color(230,231,235));
        }
        if(String.valueOf(txtPass.getPassword()).isEmpty()){
            txtPass.setText("******");
            txtPass.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void botonCrearCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearCuentaMouseEntered
        // TODO add your handling code here:
        fondoBotonCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewlogin/BotonNaranjaClaroInicio.png"))); // NOI18N
    }//GEN-LAST:event_botonCrearCuentaMouseEntered

    private void botonCrearCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearCuentaMouseExited
        // TODO add your handling code here:
        fondoBotonCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewlogin/BotonNaranjaInicio.png"))); // NOI18N
    }//GEN-LAST:event_botonCrearCuentaMouseExited

    private void botonIniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIniciarMouseEntered
        // TODO add your handling code here:
        botonIniciar.setForeground(new Color(39,45,47));
        fondoBotonIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewlogin/BotonPresionadoAmarilloCrearCuenta.png"))); // NOI18N
    }//GEN-LAST:event_botonIniciarMouseEntered

    private void botonIniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIniciarMouseExited
        // TODO add your handling code here:
        botonIniciar.setForeground(new Color(230,231,235));
        fondoBotonIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewlogin/BotonAmarilloCrearCuenta.png"))); // NOI18N
    }//GEN-LAST:event_botonIniciarMouseExited

    private void txtPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMousePressed
        // TODO add your handling code here:
        if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtApellido.getText().isEmpty()){
            txtApellido.setText("Apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(Color.LIGHT_GRAY);
        }
        if(String.valueOf(txtPass.getPassword()).equals("******")){
            txtPass.setText("");
            txtPass.setForeground(new Color(230,231,235));
        }
    }//GEN-LAST:event_txtPassMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonCrearCuenta;
    public javax.swing.JButton botonIniciar;
    private javax.swing.JLabel crearCuenta;
    public javax.swing.JLabel fondoBotonCrear;
    public javax.swing.JLabel fondoBotonIniciar;
    private javax.swing.JLabel imagenDecorativa;
    private javax.swing.JLabel inputApellido;
    private javax.swing.JLabel inputCorreo;
    private javax.swing.JLabel inputNombre;
    private javax.swing.JLabel inputPass;
    private javax.swing.JLabel labelMiembro;
    private javax.swing.JLabel recuadroFondo;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
