/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewempleados;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import model.modelview.MyComboBoxRender;


/**
 *
 * @author Estefany Torres
 */
public class PanelIngresarEmpleado extends javax.swing.JPanel {


    public PanelIngresarEmpleado() {
        initComponents();
        comboBoxMunicipio .setOpaque(false);
        comboBoxMunicipio.setEditable(true);
        JTextField boxField = (JTextField)comboBoxMunicipio .getEditor().getEditorComponent();
        boxField.setBorder(BorderFactory.createEmptyBorder());
        boxField.setForeground(new Color(230,231,235));
        boxField.setBackground(new Color(0, 0, 0, 0));
        boxField.setFocusable(false);
        comboBoxMunicipio.setRenderer(new MyComboBoxRender());
        
        comboBoxSexo .setOpaque(false);
        comboBoxSexo.setEditable(true);
        boxField = (JTextField)comboBoxSexo .getEditor().getEditorComponent();
        boxField.setBorder(BorderFactory.createEmptyBorder());
        boxField.setForeground(new Color(230,231,235));
        boxField.setBackground(new Color(0, 0, 0, 0));
        boxField.setFocusable(false);
        comboBoxSexo.setRenderer(new MyComboBoxRender());
        
        comboBoxRol .setOpaque(false);
        comboBoxRol.setEditable(true);
        boxField = (JTextField)comboBoxRol .getEditor().getEditorComponent();
        boxField.setBorder(BorderFactory.createEmptyBorder());
        boxField.setForeground(new Color(230,231,235));
        boxField.setBackground(new Color(0, 0, 0, 0));
        boxField.setFocusable(false);
        comboBoxRol.setRenderer(new MyComboBoxRender());
        
        comboBoxBanco .setOpaque(false);
        comboBoxBanco.setEditable(true);
        boxField = (JTextField)comboBoxBanco .getEditor().getEditorComponent();
        boxField.setBorder(BorderFactory.createEmptyBorder());
        boxField.setForeground(new Color(230,231,235));
        boxField.setBackground(new Color(0, 0, 0, 0));
        boxField.setFocusable(false);
        comboBoxBanco.setRenderer(new MyComboBoxRender());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconoCambiarFoto = new javax.swing.JLabel();
        botonCambiarFoto = new javax.swing.JButton();
        botonGuardarCambios = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        fondoBotonRegistrar = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        labelInputCuenta = new javax.swing.JLabel();
        comboBoxBanco = new javax.swing.JComboBox<>();
        labelInputBanco = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDateFechaIngreso = new com.toedter.calendar.JDateChooser();
        labelInputFechaIngreso = new javax.swing.JLabel();
        spinnerSueldo = new javax.swing.JSpinner();
        labelInputSueldo = new javax.swing.JLabel();
        comboBoxRol = new javax.swing.JComboBox<>();
        labelInputRol = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        comboBoxSexo = new javax.swing.JComboBox<>();
        labelInputSexo = new javax.swing.JLabel();
        spinnerEdad = new javax.swing.JSpinner();
        labelInputEdad = new javax.swing.JLabel();
        comboBoxMunicipio = new javax.swing.JComboBox<>();
        labelInputMunicipio = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        labelInputTelefono = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        labelInputCedula = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        labelInputCorreo = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        labelInputApellido = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        labelInputNombre = new javax.swing.JLabel();
        labelFechaIngreso = new javax.swing.JLabel();
        labelSueldo = new javax.swing.JLabel();
        labelImagen = new javax.swing.JLabel();
        labelCirculo = new javax.swing.JLabel();
        labelTItulo = new javax.swing.JLabel();
        labelFondoTitulo = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        fondoBotonRegresar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(39, 45, 47));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoCambiarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/iconEditarRojo.png"))); // NOI18N
        add(iconoCambiarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 20, 20));

        botonCambiarFoto.setFont(new java.awt.Font("Open Sans", 2, 15)); // NOI18N
        botonCambiarFoto.setForeground(new java.awt.Color(254, 114, 76));
        botonCambiarFoto.setText("Cambiar foto       ");
        botonCambiarFoto.setBorder(null);
        botonCambiarFoto.setBorderPainted(false);
        botonCambiarFoto.setContentAreaFilled(false);
        botonCambiarFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCambiarFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(botonCambiarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 120, 20));

        botonGuardarCambios.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonGuardarCambios.setForeground(new java.awt.Color(39, 45, 47));
        botonGuardarCambios.setText("Guardar cambios");
        botonGuardarCambios.setBorder(null);
        botonGuardarCambios.setBorderPainted(false);
        botonGuardarCambios.setContentAreaFilled(false);
        botonGuardarCambios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardarCambios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonGuardarCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonGuardarCambiosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGuardarCambiosMouseExited(evt);
            }
        });
        add(botonGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 180, 48));

        botonRegistrar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(39, 45, 47));
        botonRegistrar.setText("Registrar");
        botonRegistrar.setBorder(null);
        botonRegistrar.setBorderPainted(false);
        botonRegistrar.setContentAreaFilled(false);
        botonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseExited(evt);
            }
        });
        add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 180, 48));

        fondoBotonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/botonRegistrar.png"))); // NOI18N
        add(fondoBotonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, -1, -1));

        txtNumeroCuenta.setBackground(new java.awt.Color(0,0,0,1));
        txtNumeroCuenta.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtNumeroCuenta.setForeground(java.awt.Color.lightGray);
        txtNumeroCuenta.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumeroCuenta.setText("Número de cuenta");
        txtNumeroCuenta.setBorder(null);
        txtNumeroCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNumeroCuentaMousePressed(evt);
            }
        });
        add(txtNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 260, 40));

        labelInputCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/inputMediano.png"))); // NOI18N
        add(labelInputCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, -1, -1));

        comboBoxBanco.setBackground(new java.awt.Color(86, 92, 94));
        comboBoxBanco.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        comboBoxBanco.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el banco", "BANCO OCCIDENTAL DE DESCUENTO CA.", "BANCO SOFITASA.", "BANCO PLAZA.", "DELSUR BANCO UNIVERSAL.", "FONDO COMUN BANCO UNIVERSAL.", "BANCO NACIONAL DE CREDITO.", "BANCO MERCANTIL.", "BANCO VENEZOLANO DE CREDITO.", "BANCO PROVINCIAL.", "BANCO EXTERIOR.", "BANESCO. BANCARIBE.", "BANCO CARONI.", "BANCO BICENTENARIO. ", "100 POR CIENTO BANCO.", "BANCO DEL TESORO.", "BANPLUS BANCO COMERCIAL.", "MIBANCO BANCO DE DESARROLLO.", "BANCO ACTIVO.", "BANCO DE VENEZUELA.", "BANCRECER.", "BANCAMIGA BANCO MICROFINANCIERO.", "BANCO DE LA FUERZAS ARMADAS BANFANB" }));
        comboBoxBanco.setBorder(null);
        comboBoxBanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comboBoxBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 260, 40));

        labelInputBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/inputMediano.png"))); // NOI18N
        add(labelInputBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, -1));

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 231, 235));
        jLabel1.setText("Edad");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        jDateFechaIngreso.setFont(new java.awt.Font("Open Sans Medium", 0, 13)); // NOI18N
        add(jDateFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 260, 40));

        labelInputFechaIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/inputMediano.png"))); // NOI18N
        add(labelInputFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        spinnerSueldo.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        spinnerSueldo.setModel(new javax.swing.SpinnerNumberModel(20.0d, 20.0d, 100.0d, 1.0d));
        add(spinnerSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 260, 40));

        labelInputSueldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/inputMediano.png"))); // NOI18N
        add(labelInputSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        comboBoxRol.setBackground(new java.awt.Color(86, 92, 94));
        comboBoxRol.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        comboBoxRol.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona puesto de trabajo", "Cocinero", "Bartender", "Mesonero", "Personal de servicio" }));
        comboBoxRol.setBorder(null);
        comboBoxRol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comboBoxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 260, 40));

        labelInputRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/inputMediano.png"))); // NOI18N
        add(labelInputRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 220, 10, 320));

        comboBoxSexo.setBackground(new java.awt.Color(86, 92, 94));
        comboBoxSexo.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        comboBoxSexo.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        comboBoxSexo.setBorder(null);
        comboBoxSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 170, 40));

        labelInputSexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/inputPequeno.png"))); // NOI18N
        add(labelInputSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, -1, -1));

        spinnerEdad.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        spinnerEdad.setModel(new javax.swing.SpinnerNumberModel(30, 18, 90, 1));
        add(spinnerEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 170, 40));

        labelInputEdad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/inputPequeno.png"))); // NOI18N
        add(labelInputEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, -1, -1));

        comboBoxMunicipio.setBackground(new java.awt.Color(86, 92, 94));
        comboBoxMunicipio.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        comboBoxMunicipio.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el municipio", "Baruta", "Chacao", "El Hatillo", "Libertador", "Sucre" }));
        comboBoxMunicipio.setBorder(null);
        comboBoxMunicipio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comboBoxMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 370, 40));

        labelInputMunicipio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/inputGrande.png"))); // NOI18N
        add(labelInputMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        txtTelefono.setBackground(new java.awt.Color(0,0,0,1));
        txtTelefono.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtTelefono.setForeground(java.awt.Color.lightGray);
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelefono.setText("Teléfono");
        txtTelefono.setBorder(null);
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 170, 40));

        labelInputTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/inputPequeno.png"))); // NOI18N
        add(labelInputTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        txtCedula.setBackground(new java.awt.Color(0,0,0,1));
        txtCedula.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtCedula.setForeground(java.awt.Color.lightGray);
        txtCedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCedula.setText("Cédula");
        txtCedula.setBorder(null);
        txtCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedulaMousePressed(evt);
            }
        });
        add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 170, 40));

        labelInputCedula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/inputPequeno.png"))); // NOI18N
        add(labelInputCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(0,0,0,1));
        txtCorreo.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtCorreo.setForeground(java.awt.Color.lightGray);
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCorreo.setText("Correo");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 370, 40));

        labelInputCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/inputGrande.png"))); // NOI18N
        add(labelInputCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        txtApellido.setBackground(new java.awt.Color(0,0,0,1));
        txtApellido.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtApellido.setForeground(java.awt.Color.lightGray);
        txtApellido.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellido.setText("Apellido");
        txtApellido.setBorder(null);
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoMousePressed(evt);
            }
        });
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 170, 40));

        labelInputApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/inputPequeno.png"))); // NOI18N
        add(labelInputApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        txtNombre.setBackground(new java.awt.Color(0,0,0,1));
        txtNombre.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        txtNombre.setForeground(java.awt.Color.lightGray);
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setText("Nombre");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 170, 40));

        labelInputNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/inputPequeno.png"))); // NOI18N
        add(labelInputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        labelFechaIngreso.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        labelFechaIngreso.setForeground(new java.awt.Color(230, 231, 235));
        labelFechaIngreso.setText("Fecha de Ingreso");
        add(labelFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        labelSueldo.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        labelSueldo.setForeground(new java.awt.Color(230, 231, 235));
        labelSueldo.setText("Sueldo por día ($)");
        add(labelSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        labelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/imagenUser.png"))); // NOI18N
        add(labelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 49, 130, 130));

        labelCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/circuloRojo.png"))); // NOI18N
        add(labelCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 130, -1));

        labelTItulo.setBackground(new java.awt.Color(0, 0, 0));
        labelTItulo.setFont(new java.awt.Font("Open Sans Medium", 1, 20)); // NOI18N
        labelTItulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTItulo.setText("DATOS DEL EMPLEADO");
        add(labelTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 460, 20));

        labelFondoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/fondoTItuloDetalles.png"))); // NOI18N
        add(labelFondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 750, -1));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/fondoPanelIngresar.png"))); // NOI18N
        add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 750, 640));

        botonRegresar.setFont(new java.awt.Font("Open Sans SemiBold", 0, 15)); // NOI18N
        botonRegresar.setForeground(new java.awt.Color(230, 231, 235));
        botonRegresar.setBorder(null);
        botonRegresar.setBorderPainted(false);
        botonRegresar.setContentAreaFilled(false);
        botonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresarMouseExited(evt);
            }
        });
        add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 50, 50));

        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/botonRegresar.png"))); // NOI18N
        add(fondoBotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        // TODO add your handling code here:
        if(txtNombre.getText().equals("Nombre")){
            txtNombre.setText("");
            txtNombre.setForeground(new Color(230,231,235));
        }
        
        if(txtApellido.getText().isEmpty()){
            txtApellido.setText("Apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCedula.getText().isEmpty()){
            txtCedula.setText("Cédula");
            txtCedula.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Teléfono");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtNumeroCuenta.getText().isEmpty()){
            txtNumeroCuenta.setText("Número de cuenta");
            txtNumeroCuenta.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMousePressed
        // TODO add your handling code here:
        if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtApellido.getText().equals("Apellido")){
            txtApellido.setText("");
            txtApellido.setForeground(new Color(230,231,235));
        }
        
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCedula.getText().isEmpty()){
            txtCedula.setText("Cédula");
            txtCedula.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Teléfono");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtNumeroCuenta.getText().isEmpty()){
            txtNumeroCuenta.setText("Número de cuenta");
            txtNumeroCuenta.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtApellidoMousePressed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
         if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtApellido.getText().isEmpty()){
            txtApellido.setText("Apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCorreo.getText().equals("Correo")){
            txtCorreo.setText("");
            txtCorreo.setForeground(new Color(230,231,235));
        }
        
        if(txtCedula.getText().isEmpty()){
            txtCedula.setText("Cédula");
            txtCedula.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Teléfono");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
       
        if(txtNumeroCuenta.getText().isEmpty()){
            txtNumeroCuenta.setText("Número de cuenta");
            txtNumeroCuenta.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaMousePressed
        // TODO add your handling code here:
         if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtApellido.getText().isEmpty()){
            txtApellido.setText("Apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCedula.getText().equals("Cédula")){
            txtCedula.setText("");
            txtCedula.setForeground(new Color(230,231,235));
        }
        
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Teléfono");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtNumeroCuenta.getText().isEmpty()){
            txtNumeroCuenta.setText("Número de cuenta");
            txtNumeroCuenta.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtCedulaMousePressed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        // TODO add your handling code here:
         if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtApellido.getText().isEmpty()){
            txtApellido.setText("Apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCedula.getText().isEmpty()){
            txtCedula.setText("Cédula");
            txtCedula.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtTelefono.getText().equals("Teléfono")){
            txtTelefono.setText("");
            txtTelefono.setForeground(new Color(230,231,235));
        }
        
        if(txtNumeroCuenta.getText().isEmpty()){
            txtNumeroCuenta.setText("Número de cuenta");
            txtNumeroCuenta.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void txtNumeroCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroCuentaMousePressed
        // TODO add your handling code here:
         if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Nombre");
            txtNombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtApellido.getText().isEmpty()){
            txtApellido.setText("Apellido");
            txtApellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtCedula.getText().isEmpty()){
            txtCedula.setText("Cédula");
            txtCedula.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Teléfono");
            txtTelefono.setForeground(Color.LIGHT_GRAY);
        }
        
        if(txtNumeroCuenta.getText().equals("Número de cuenta")){
            txtNumeroCuenta.setText("");
            txtNumeroCuenta.setForeground(new Color(230,231,235));
        }
    }//GEN-LAST:event_txtNumeroCuentaMousePressed

    private void botonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseEntered
        // TODO add your handling code here:
        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/botonRegresarPresionado.png"))); // NOI18N
        
    }//GEN-LAST:event_botonRegresarMouseEntered

    private void botonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseExited
        // TODO add your handling code here:
        fondoBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/botonRegresar.png"))); // NOI18N
    }//GEN-LAST:event_botonRegresarMouseExited

    private void botonRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseEntered
        // TODO add your handling code here:
        fondoBotonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/botonRegistrarPresionado.png"))); // NOI18N
    }//GEN-LAST:event_botonRegistrarMouseEntered

    private void botonRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseExited
        // TODO add your handling code here:
        fondoBotonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/botonRegistrar.png"))); // NOI18N
    }//GEN-LAST:event_botonRegistrarMouseExited

    private void botonGuardarCambiosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarCambiosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarCambiosMouseEntered

    private void botonGuardarCambiosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarCambiosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarCambiosMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonCambiarFoto;
    public javax.swing.JButton botonGuardarCambios;
    public javax.swing.JButton botonRegistrar;
    public javax.swing.JButton botonRegresar;
    public javax.swing.JComboBox<String> comboBoxBanco;
    public javax.swing.JComboBox<String> comboBoxMunicipio;
    public javax.swing.JComboBox<String> comboBoxRol;
    public javax.swing.JComboBox<String> comboBoxSexo;
    private javax.swing.JLabel fondoBotonRegistrar;
    private javax.swing.JLabel fondoBotonRegresar;
    private javax.swing.JLabel iconoCambiarFoto;
    public com.toedter.calendar.JDateChooser jDateFechaIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelCirculo;
    private javax.swing.JLabel labelFechaIngreso;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelFondoTitulo;
    public javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelInputApellido;
    private javax.swing.JLabel labelInputBanco;
    private javax.swing.JLabel labelInputCedula;
    private javax.swing.JLabel labelInputCorreo;
    private javax.swing.JLabel labelInputCuenta;
    private javax.swing.JLabel labelInputEdad;
    private javax.swing.JLabel labelInputFechaIngreso;
    private javax.swing.JLabel labelInputMunicipio;
    private javax.swing.JLabel labelInputNombre;
    private javax.swing.JLabel labelInputRol;
    private javax.swing.JLabel labelInputSexo;
    private javax.swing.JLabel labelInputSueldo;
    private javax.swing.JLabel labelInputTelefono;
    private javax.swing.JLabel labelSueldo;
    public javax.swing.JLabel labelTItulo;
    public javax.swing.JSpinner spinnerEdad;
    public javax.swing.JSpinner spinnerSueldo;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNumeroCuenta;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
