/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewempleados;

/**
 *
 * @author Estefany Torres
 */
public class PanelEmpleado extends javax.swing.JPanel {

    public PanelEmpleado() {
        initComponents();
        fondoEmpleadoPresionado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonEmpleado = new javax.swing.JButton();
        iconoEmpleado = new javax.swing.JLabel();
        fondoEmpleadoPresionado = new javax.swing.JLabel();
        fondoEmpleado = new javax.swing.JLabel();
        labelCedula = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonEmpleado.setFont(new java.awt.Font("Open Sans SemiBold", 0, 16)); // NOI18N
        botonEmpleado.setForeground(new java.awt.Color(230, 231, 235));
        botonEmpleado.setText("Usuario");
        botonEmpleado.setBorder(null);
        botonEmpleado.setBorderPainted(false);
        botonEmpleado.setContentAreaFilled(false);
        botonEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEmpleadoMouseExited(evt);
            }
        });
        add(botonEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 9, 230, 60));

        iconoEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/iconoEmpleado.png"))); // NOI18N
        add(iconoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 19, -1, 40));

        fondoEmpleadoPresionado.setBackground(new java.awt.Color(102, 102, 102));
        fondoEmpleadoPresionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoEmpleadoPresionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/fondoNombreEmpleado.png"))); // NOI18N
        add(fondoEmpleadoPresionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 9, 280, 60));

        fondoEmpleado.setBackground(new java.awt.Color(102, 102, 102));
        fondoEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/fondoNombreEmpleado.png"))); // NOI18N
        add(fondoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 9, 280, 60));
        add(labelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEmpleadoMouseEntered
        // TODO add your handling code here:
        fondoEmpleadoPresionado.setVisible(true);
    }//GEN-LAST:event_botonEmpleadoMouseEntered

    private void botonEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEmpleadoMouseExited
        // TODO add your handling code here:
        fondoEmpleadoPresionado.setVisible(false);
    }//GEN-LAST:event_botonEmpleadoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonEmpleado;
    private javax.swing.JLabel fondoEmpleado;
    private javax.swing.JLabel fondoEmpleadoPresionado;
    private javax.swing.JLabel iconoEmpleado;
    public javax.swing.JLabel labelCedula;
    // End of variables declaration//GEN-END:variables
}
