/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.viewempleados;

/**
 *
 * @author Estefany Torres
 */
public class PanelNomina extends javax.swing.JPanel {

    public PanelNomina() {
        initComponents();
        fondoNominaPresionado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFecha = new javax.swing.JLabel();
        botonNomina = new javax.swing.JButton();
        iconoNomina = new javax.swing.JLabel();
        fondoNominaPresionado = new javax.swing.JLabel();
        fondoNomina = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelFecha.setFont(new java.awt.Font("Open Sans SemiBold", 0, 13)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(230, 231, 235));
        labelFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelFecha.setText("03/07/23 al 09/07/23");
        add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 170, 40));

        botonNomina.setFont(new java.awt.Font("Open Sans SemiBold", 0, 16)); // NOI18N
        botonNomina.setForeground(new java.awt.Color(230, 231, 235));
        botonNomina.setBorder(null);
        botonNomina.setBorderPainted(false);
        botonNomina.setContentAreaFilled(false);
        botonNomina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonNomina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonNomina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonNominaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonNominaMouseExited(evt);
            }
        });
        botonNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNominaActionPerformed(evt);
            }
        });
        add(botonNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 60));

        iconoNomina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/iconoNominaBlanco.png"))); // NOI18N
        add(iconoNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        fondoNominaPresionado.setBackground(new java.awt.Color(102, 102, 102));
        fondoNominaPresionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoNominaPresionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/fondoNombreNomina.png"))); // NOI18N
        add(fondoNominaPresionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 60));

        fondoNomina.setBackground(new java.awt.Color(102, 102, 102));
        fondoNomina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoNomina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagesviewempleados/fondoNombreNomina.png"))); // NOI18N
        add(fondoNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void botonNominaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNominaMouseEntered
        // TODO add your handling code here:
        fondoNominaPresionado.setVisible(true);
    }//GEN-LAST:event_botonNominaMouseEntered

    private void botonNominaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNominaMouseExited
        // TODO add your handling code here:
        fondoNominaPresionado.setVisible(false);
    }//GEN-LAST:event_botonNominaMouseExited

    private void botonNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNominaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonNomina;
    private javax.swing.JLabel fondoNomina;
    private javax.swing.JLabel fondoNominaPresionado;
    private javax.swing.JLabel iconoNomina;
    public javax.swing.JLabel labelFecha;
    // End of variables declaration//GEN-END:variables
}
